/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif


// Split enums from the rest of the header so they can be included earlier
// than the rest of the header file by including this file twice with different
// #define wrappers. See Engine.h and look at EngineClasses.h for an example.
#if !NO_ENUMS && !defined(NAMES_ONLY)


#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern FName AVAGAME_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

class UavaSeqAct_SetHm : public USeqAct_SetSequenceVariable
{
public:
    //## BEGIN PROPS avaSeqAct_SetHm
    BITFIELD DefaultValue:1;
    //## END PROPS avaSeqAct_SetHm

    DECLARE_CLASS(UavaSeqAct_SetHm,USeqAct_SetSequenceVariable,0,avaGame)
	void Activated();
};

class UavaSeqAct_SetHmInt : public USeqAct_SetSequenceVariable
{
public:
    //## BEGIN PROPS avaSeqAct_SetHmInt
    INT Value;
    //## END PROPS avaSeqAct_SetHmInt

    DECLARE_CLASS(UavaSeqAct_SetHmInt,USeqAct_SetSequenceVariable,0,avaGame)
	void Activated();
};

class UavaSeqVar_Hm : public USequenceVariable
{
public:
    //## BEGIN PROPS avaSeqVar_Hm
    INT bValue;
    //## END PROPS avaSeqVar_Hm

    DECLARE_CLASS(UavaSeqVar_Hm,USequenceVariable,0,avaGame)
	void retrieveValue(void);
	UBOOL* GetBoolRef();
	/*
	{
		return (UBOOL*)&bValue;
	}
	*/

	FString GetValueStr();
	/*
	{
		return bValue == TRUE ? GTrue : GFalse;
	}
	*/

	virtual UBOOL SupportsProperty(UProperty *Property)
	{
		return (Property->IsA(UBoolProperty::StaticClass()));
	}

	virtual void PublishValue(USequenceOp *Op, UProperty *Property, FSeqVarLink &VarLink);
	virtual void PopulateValue(USequenceOp *Op, UProperty *Property, FSeqVarLink &VarLink);
};

class UavaSeqVar_HmInt : public USequenceVariable
{
public:
    //## BEGIN PROPS avaSeqVar_HmInt
    INT IntValue;
    //## END PROPS avaSeqVar_HmInt

    DECLARE_CLASS(UavaSeqVar_HmInt,USequenceVariable,0,avaGame)
	void retrieveValue(void);
	virtual INT* GetIntRef();
	/*
	{
		return &IntValue;
	}
	*/

	virtual FString GetValueStr();
	/*
	{
		return FString::Printf(TEXT("%d"),IntValue);
	}
	*/

	virtual UBOOL SupportsProperty(UProperty *Property)
	{
		return (Property->IsA(UIntProperty::StaticClass()));
	}

	virtual void PublishValue(USequenceOp *Op, UProperty *Property, FSeqVarLink &VarLink);
	virtual void PopulateValue(USequenceOp *Op, UProperty *Property, FSeqVarLink &VarLink);
};

#endif


#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef AVAGAME_SEQUENCE_NATIVE_DEFS
#define AVAGAME_SEQUENCE_NATIVE_DEFS

DECLARE_NATIVE_TYPE(avaGame,UavaSeqAct_SetHm);
DECLARE_NATIVE_TYPE(avaGame,UavaSeqAct_SetHmInt);
DECLARE_NATIVE_TYPE(avaGame,UavaSeqVar_Hm);
DECLARE_NATIVE_TYPE(avaGame,UavaSeqVar_HmInt);

#define AUTO_INITIALIZE_REGISTRANTS_AVAGAME_SEQUENCE \
	UavaSeqAct_SetHm::StaticClass(); \
	UavaSeqAct_SetHmInt::StaticClass(); \
	UavaSeqVar_Hm::StaticClass(); \
	UavaSeqVar_HmInt::StaticClass(); \

#endif // AVAGAME_SEQUENCE_NATIVE_DEFS

#ifdef NATIVES_ONLY
#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(UavaSeqAct_SetHm)
VERIFY_CLASS_OFFSET_NODIE(U,avaSeqAct_SetHmInt,Value)
VERIFY_CLASS_SIZE_NODIE(UavaSeqAct_SetHmInt)
VERIFY_CLASS_OFFSET_NODIE(U,avaSeqVar_Hm,bValue)
VERIFY_CLASS_SIZE_NODIE(UavaSeqVar_Hm)
VERIFY_CLASS_OFFSET_NODIE(U,avaSeqVar_HmInt,IntValue)
VERIFY_CLASS_SIZE_NODIE(UavaSeqVar_HmInt)
#endif // VERIFY_CLASS_SIZES
#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
