/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif


// Split enums from the rest of the header so they can be included earlier
// than the rest of the header file by including this file twice with different
// #define wrappers. See Engine.h and look at EngineClasses.h for an example.
#if !NO_ENUMS && !defined(NAMES_ONLY)


#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern FName AVAGAME_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

class UavaGBType_DSPPreset : public UGenericBrowserType
{
public:
    //## BEGIN PROPS avaGBType_DSPPreset
    //## END PROPS avaGBType_DSPPreset

    DECLARE_CLASS(UavaGBType_DSPPreset,UGenericBrowserType,0,avaGame)
	virtual void Init();
	virtual UBOOL ShowObjectEditor( UObject* InObject );
	void InvokeCustomCommand( INT InCommand, UObject* InObject );
};

class UavaGBType_SoundScapeProperty : public UGenericBrowserType
{
public:
    //## BEGIN PROPS avaGBType_SoundScapeProperty
    //## END PROPS avaGBType_SoundScapeProperty

    DECLARE_CLASS(UavaGBType_SoundScapeProperty,UGenericBrowserType,0,avaGame)
	virtual void Init();
	virtual UBOOL ShowObjectEditor( UObject* InObject );
};

#endif


#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef AVAGAME_EDITOR_NATIVE_DEFS
#define AVAGAME_EDITOR_NATIVE_DEFS

DECLARE_NATIVE_TYPE(avaGame,UavaGBType_DSPPreset);
DECLARE_NATIVE_TYPE(avaGame,UavaGBType_SoundScapeProperty);

#define AUTO_INITIALIZE_REGISTRANTS_AVAGAME_EDITOR \
	UavaGBType_DSPPreset::StaticClass(); \
	UavaGBType_SoundScapeProperty::StaticClass(); \

#endif // AVAGAME_EDITOR_NATIVE_DEFS

#ifdef NATIVES_ONLY
#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(UavaGBType_DSPPreset)
VERIFY_CLASS_SIZE_NODIE(UavaGBType_SoundScapeProperty)
#endif // VERIFY_CLASS_SIZES
#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
