/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif


// Split enums from the rest of the header so they can be included earlier
// than the rest of the header file by including this file twice with different
// #define wrappers. See Engine.h and look at EngineClasses.h for an example.
#if !NO_ENUMS && !defined(NAMES_ONLY)

enum ESceneDepthPriorityGroup
{
    SDPG_UnrealEdBackground =0,
    SDPG_World              =1,
    SDPG_Foreground         =2,
    SDPG_UnrealEdForeground =3,
    SDPG_PostProcess        =4,
    SDPG_SkyLayer0          =5,
    SDPG_SkyLayer1          =6,
    SDPG_SkyLayer2          =7,
    SDPG_SkyLayer3          =8,
    SDPG_ForeForeground     =9,
    SDPG_MAX                =10,
};

#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern FName ENGINE_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

#define UCONST_SDPG_NumBits 4

class UScene : public UObject
{
public:
    //## BEGIN PROPS Scene
    //## END PROPS Scene

    DECLARE_CLASS(UScene,UObject,0,Engine)
    NO_DEFAULT_CONSTRUCTOR(UScene)
};

#endif


#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef ENGINE_SCENE_NATIVE_DEFS
#define ENGINE_SCENE_NATIVE_DEFS

DECLARE_NATIVE_TYPE(Engine,UScene);

#define AUTO_INITIALIZE_REGISTRANTS_ENGINE_SCENE \
	UScene::StaticClass(); \

#endif // ENGINE_SCENE_NATIVE_DEFS

#ifdef NATIVES_ONLY
#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(UScene)
#endif // VERIFY_CLASS_SIZES
#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
