/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif


// Split enums from the rest of the header so they can be included earlier
// than the rest of the header file by including this file twice with different
// #define wrappers. See Engine.h and look at EngineClasses.h for an example.
#if !NO_ENUMS && !defined(NAMES_ONLY)

enum ESceneTextureType
{
    SceneTex_Lighting       =0,
    SceneTex_MAX            =1,
};
enum EMaterialVectorCoordTransform
{
    TRANSFORM_World         =0,
    TRANSFORM_View          =1,
    TRANSFORM_Local         =2,
    TRANSFORM_MAX           =3,
};

#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern FName ENGINE_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

class UMaterialExpressionAbs : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionAbs
    FExpressionInput Input;
    //## END PROPS MaterialExpressionAbs

    DECLARE_CLASS(UMaterialExpressionAbs,UMaterialExpression,0,Engine)
    /**
	 * Creates the new shader code chunk needed for the Abs expression
	 *
	 * @param	Compiler - Material compiler that knows how to handle this expression
	 * @return	Index to the new FMaterialCompiler::CodeChunk entry for this expression
	 */	
	virtual INT Compile( FMaterialCompiler* Compiler );

	/**
	 * Textual description for this material expression
	 *
	 * @return	Caption text
	 */	
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionAdd : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionAdd
    FExpressionInput A;
    FExpressionInput B;
    //## END PROPS MaterialExpressionAdd

    DECLARE_CLASS(UMaterialExpressionAdd,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionAppendVector : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionAppendVector
    FExpressionInput A;
    FExpressionInput B;
    //## END PROPS MaterialExpressionAppendVector

    DECLARE_CLASS(UMaterialExpressionAppendVector,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionBumpOffset : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionBumpOffset
    FExpressionInput Coordinate;
    FExpressionInput Height;
    FLOAT HeightRatio;
    FLOAT ReferencePlane;
    //## END PROPS MaterialExpressionBumpOffset

    DECLARE_CLASS(UMaterialExpressionBumpOffset,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionCameraVector : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionCameraVector
    //## END PROPS MaterialExpressionCameraVector

    DECLARE_CLASS(UMaterialExpressionCameraVector,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;
};

class UMaterialExpressionCeil : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionCeil
    FExpressionInput Input;
    //## END PROPS MaterialExpressionCeil

    DECLARE_CLASS(UMaterialExpressionCeil,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionClamp : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionClamp
    FExpressionInput Input;
    FExpressionInput Min;
    FExpressionInput Max;
    //## END PROPS MaterialExpressionClamp

    DECLARE_CLASS(UMaterialExpressionClamp,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionComment : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionComment
    INT PosX;
    INT PosY;
    INT SizeX;
    INT SizeY;
    FStringNoInit Text;
    //## END PROPS MaterialExpressionComment

    DECLARE_CLASS(UMaterialExpressionComment,UMaterialExpression,0,Engine)
	/**
	 * Text description of this expression.
	 */
	virtual FString GetCaption() const;
};

class UMaterialExpressionComponentMask : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionComponentMask
    FExpressionInput Input;
    BITFIELD R:1;
    BITFIELD G:1;
    BITFIELD B:1;
    BITFIELD A:1;
    //## END PROPS MaterialExpressionComponentMask

    DECLARE_CLASS(UMaterialExpressionComponentMask,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionCompound : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionCompound
    TArrayNoInit<class UMaterialExpression*> MaterialExpressions;
    FStringNoInit Caption;
    BITFIELD bExpanded:1;
    //## END PROPS MaterialExpressionCompound

    DECLARE_CLASS(UMaterialExpressionCompound,UMaterialExpression,0,Engine)
	/**
	 * Textual description for this material expression
	 *
	 * @return	Caption text
	 */	
	virtual FString GetCaption() const;
	
	/**
	 * Recursively gathers all UMaterialExpression objects referenced by this expression.
	 * Including self.
	 *
	 * @param	Expressions	- Reference to array of material expressions to add to
	 */	
	virtual void GetExpressions( TArray<const UMaterialExpression*>& Expressions ) const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionConstant : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionConstant
    FLOAT R;
    //## END PROPS MaterialExpressionConstant

    DECLARE_CLASS(UMaterialExpressionConstant,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;
};

class UMaterialExpressionConstant2Vector : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionConstant2Vector
    FLOAT R;
    FLOAT G;
    //## END PROPS MaterialExpressionConstant2Vector

    DECLARE_CLASS(UMaterialExpressionConstant2Vector,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;
};

class UMaterialExpressionConstant3Vector : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionConstant3Vector
    FLOAT R;
    FLOAT G;
    FLOAT B;
    //## END PROPS MaterialExpressionConstant3Vector

    DECLARE_CLASS(UMaterialExpressionConstant3Vector,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;
};

class UMaterialExpressionConstant4Vector : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionConstant4Vector
    FLOAT R;
    FLOAT G;
    FLOAT B;
    FLOAT A;
    //## END PROPS MaterialExpressionConstant4Vector

    DECLARE_CLASS(UMaterialExpressionConstant4Vector,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;
};

class UMaterialExpressionCosine : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionCosine
    FExpressionInput Input;
    FLOAT Period;
    //## END PROPS MaterialExpressionCosine

    DECLARE_CLASS(UMaterialExpressionCosine,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionCrossProduct : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionCrossProduct
    FExpressionInput A;
    FExpressionInput B;
    //## END PROPS MaterialExpressionCrossProduct

    DECLARE_CLASS(UMaterialExpressionCrossProduct,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionDepthBiasedAlpha : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionDepthBiasedAlpha
    BITFIELD bNormalize:1;
    FLOAT BiasScale;
    FExpressionInput Alpha;
    FExpressionInput Bias;
    //## END PROPS MaterialExpressionDepthBiasedAlpha

    DECLARE_CLASS(UMaterialExpressionDepthBiasedAlpha,UMaterialExpression,0,Engine)
	/**
	 *	Compile the material expression
	 *
	 *	@param	Compiler	Pointer to the material compiler to use
	 *
	 *	@return	INT			The compiled code index
	 */	
	virtual INT Compile(FMaterialCompiler* Compiler);

	/**
	 */	
	virtual INT GetWidth() const;

	/**
	 */	
	virtual FString GetCaption() const;

	/**
	 */	
	virtual INT GetLabelPadding() { return 8; }

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionDepthBiasedBlend : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionDepthBiasedBlend
    BITFIELD bNormalize:1;
    FLOAT BiasScale;
    FExpressionInput RGB;
    FExpressionInput Alpha;
    FExpressionInput Bias;
    //## END PROPS MaterialExpressionDepthBiasedBlend

    DECLARE_CLASS(UMaterialExpressionDepthBiasedBlend,UMaterialExpression,0,Engine)
	/**
	 *	Compile the material expression
	 *
	 *	@param	Compiler	Pointer to the material compiler to use
	 *
	 *	@return	INT			The compiled code index
	 */	
	virtual INT Compile(FMaterialCompiler* Compiler);

	/**
	 *	Get the outputs associated with the expression
	 *
	 *	@param	Outputs		The array that contains the output expression
	 */	
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;

	/**
	 */	
	virtual INT GetWidth() const;

	/**
	 */	
	virtual FString GetCaption() const;

	/**
	 */	
	virtual INT GetLabelPadding() { return 8; }

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionDesaturation : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionDesaturation
    FExpressionInput Input;
    FExpressionInput Percent;
    FLinearColor LuminanceFactors;
    //## END PROPS MaterialExpressionDesaturation

    DECLARE_CLASS(UMaterialExpressionDesaturation,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const
	{
		return TEXT("Desaturation");
	}

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionDestColor : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionDestColor
    //## END PROPS MaterialExpressionDestColor

    DECLARE_CLASS(UMaterialExpressionDestColor,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;
	virtual FString GetCaption() const;
};

class UMaterialExpressionDestDepth : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionDestDepth
    BITFIELD bNormalize:1;
    //## END PROPS MaterialExpressionDestDepth

    DECLARE_CLASS(UMaterialExpressionDestDepth,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;
	virtual FString GetCaption() const;
};

class UMaterialExpressionDivide : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionDivide
    FExpressionInput A;
    FExpressionInput B;
    //## END PROPS MaterialExpressionDivide

    DECLARE_CLASS(UMaterialExpressionDivide,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionDotProduct : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionDotProduct
    FExpressionInput A;
    FExpressionInput B;
    //## END PROPS MaterialExpressionDotProduct

    DECLARE_CLASS(UMaterialExpressionDotProduct,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionEnvCube : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionEnvCube
    FExpressionInput Coordinates;
    //## END PROPS MaterialExpressionEnvCube

    DECLARE_CLASS(UMaterialExpressionEnvCube,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );

	virtual FString GetCaption() const;
};

class UMaterialExpressionFallback : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionFallback
    FExpressionInput PCD3D;
    FExpressionInput PCD3D_SM2;
    FExpressionInput PCD3D_SM2_POOR;
    FExpressionInput PS3;
    FExpressionInput XBOXD3D;
    FExpressionInput DefaultCase;
    //## END PROPS MaterialExpressionFallback

    DECLARE_CLASS(UMaterialExpressionFallback,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionFloor : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionFloor
    FExpressionInput Input;
    //## END PROPS MaterialExpressionFloor

    DECLARE_CLASS(UMaterialExpressionFloor,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionFrac : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionFrac
    FExpressionInput Input;
    //## END PROPS MaterialExpressionFrac

    DECLARE_CLASS(UMaterialExpressionFrac,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionFresnel : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionFresnel
    FLOAT Exponent;
    FExpressionInput Normal;
    //## END PROPS MaterialExpressionFresnel

    DECLARE_CLASS(UMaterialExpressionFresnel,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const
	{
		return FString(TEXT("Fresnel"));
	}

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionIf : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionIf
    FExpressionInput A;
    FExpressionInput B;
    FExpressionInput AGreaterThanB;
    FExpressionInput AEqualsB;
    FExpressionInput ALessThanB;
    //## END PROPS MaterialExpressionIf

    DECLARE_CLASS(UMaterialExpressionIf,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionLensFlareIntensity : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionLensFlareIntensity
    //## END PROPS MaterialExpressionLensFlareIntensity

    DECLARE_CLASS(UMaterialExpressionLensFlareIntensity,UMaterialExpression,0,Engine)
	/**
	 *	Compile this expression with the given compiler.
	 *	
	 *	@return	INT			The code index for this expression.
	 */
	virtual INT Compile(FMaterialCompiler* Compiler);
	
	/**
	 *	Get the outputs supported by this expression.
	 *
	 *	@param	Outputs		The TArray of outputs to fill in.
	 */
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;
	
	/**
	 *	Get the width required by this expression (in the material editor).
	 *
	 *	@return	INT			The width in pixels.
	 */
	virtual INT GetWidth() const;
	
	/**
	 *	Returns the text to display on the material expression (in the material editor).
	 *
	 *	@return	FString		The text to display.
	 */
	virtual FString GetCaption() const;
	
	/**
	 *	Returns the amount of padding to use for the label.
	 *
	 *	@return INT			The padding (in pixels).
	 */
	virtual INT GetLabelPadding() { return 8; }
};

class UMaterialExpressionLensFlareRadialDistance : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionLensFlareRadialDistance
    //## END PROPS MaterialExpressionLensFlareRadialDistance

    DECLARE_CLASS(UMaterialExpressionLensFlareRadialDistance,UMaterialExpression,0,Engine)
	/**
	 *	Compile this expression with the given compiler.
	 *	
	 *	@return	INT			The code index for this expression.
	 */
	virtual INT Compile(FMaterialCompiler* Compiler);
	
	/**
	 *	Get the outputs supported by this expression.
	 *
	 *	@param	Outputs		The TArray of outputs to fill in.
	 */
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;
	
	/**
	 *	Get the width required by this expression (in the material editor).
	 *
	 *	@return	INT			The width in pixels.
	 */
	virtual INT GetWidth() const;
	
	/**
	 *	Returns the text to display on the material expression (in the material editor).
	 *
	 *	@return	FString		The text to display.
	 */
	virtual FString GetCaption() const;
	
	/**
	 *	Returns the amount of padding to use for the label.
	 *
	 *	@return INT			The padding (in pixels).
	 */
	virtual INT GetLabelPadding() { return 8; }
};

class UMaterialExpressionLensFlareRayDistance : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionLensFlareRayDistance
    //## END PROPS MaterialExpressionLensFlareRayDistance

    DECLARE_CLASS(UMaterialExpressionLensFlareRayDistance,UMaterialExpression,0,Engine)
	/**
	 *	Compile this expression with the given compiler.
	 *	
	 *	@return	INT			The code index for this expression.
	 */
	virtual INT Compile(FMaterialCompiler* Compiler);
	
	/**
	 *	Get the outputs supported by this expression.
	 *
	 *	@param	Outputs		The TArray of outputs to fill in.
	 */
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;
	
	/**
	 *	Get the width required by this expression (in the material editor).
	 *
	 *	@return	INT			The width in pixels.
	 */
	virtual INT GetWidth() const;
	
	/**
	 *	Returns the text to display on the material expression (in the material editor).
	 *
	 *	@return	FString		The text to display.
	 */
	virtual FString GetCaption() const;
	
	/**
	 *	Returns the amount of padding to use for the label.
	 *
	 *	@return INT			The padding (in pixels).
	 */
	virtual INT GetLabelPadding() { return 8; }
};

class UMaterialExpressionLensFlareSourceDistance : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionLensFlareSourceDistance
    //## END PROPS MaterialExpressionLensFlareSourceDistance

    DECLARE_CLASS(UMaterialExpressionLensFlareSourceDistance,UMaterialExpression,0,Engine)
	/**
	 *	Compile this expression with the given compiler.
	 *	
	 *	@return	INT			The code index for this expression.
	 */
	virtual INT Compile(FMaterialCompiler* Compiler);
	
	/**
	 *	Get the outputs supported by this expression.
	 *
	 *	@param	Outputs		The TArray of outputs to fill in.
	 */
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;
	
	/**
	 *	Get the width required by this expression (in the material editor).
	 *
	 *	@return	INT			The width in pixels.
	 */
	virtual INT GetWidth() const;
	
	/**
	 *	Returns the text to display on the material expression (in the material editor).
	 *
	 *	@return	FString		The text to display.
	 */
	virtual FString GetCaption() const;
	
	/**
	 *	Returns the amount of padding to use for the label.
	 *
	 *	@return INT			The padding (in pixels).
	 */
	virtual INT GetLabelPadding() { return 8; }
};

class UMaterialExpressionLightVector : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionLightVector
    //## END PROPS MaterialExpressionLightVector

    DECLARE_CLASS(UMaterialExpressionLightVector,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;
};

class UMaterialExpressionLinearInterpolate : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionLinearInterpolate
    FExpressionInput A;
    FExpressionInput B;
    FExpressionInput Alpha;
    //## END PROPS MaterialExpressionLinearInterpolate

    DECLARE_CLASS(UMaterialExpressionLinearInterpolate,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionMeshEmitterVertexColor : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionMeshEmitterVertexColor
    //## END PROPS MaterialExpressionMeshEmitterVertexColor

    DECLARE_CLASS(UMaterialExpressionMeshEmitterVertexColor,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;
};

class UMaterialExpressionMultiply : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionMultiply
    FExpressionInput A;
    FExpressionInput B;
    //## END PROPS MaterialExpressionMultiply

    DECLARE_CLASS(UMaterialExpressionMultiply,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionNormalize : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionNormalize
    FExpressionInput VectorInput;
    //## END PROPS MaterialExpressionNormalize

    DECLARE_CLASS(UMaterialExpressionNormalize,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const { return TEXT("Normalize"); }

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionOneMinus : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionOneMinus
    FExpressionInput Input;
    //## END PROPS MaterialExpressionOneMinus

    DECLARE_CLASS(UMaterialExpressionOneMinus,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionPanner : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionPanner
    FExpressionInput Coordinate;
    FExpressionInput Time;
    FLOAT SpeedX;
    FLOAT SpeedY;
    //## END PROPS MaterialExpressionPanner

    DECLARE_CLASS(UMaterialExpressionPanner,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionPixelDepth : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionPixelDepth
    BITFIELD bNormalize:1;
    //## END PROPS MaterialExpressionPixelDepth

    DECLARE_CLASS(UMaterialExpressionPixelDepth,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;
	virtual FString GetCaption() const;
};

class UMaterialExpressionPower : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionPower
    FExpressionInput Base;
    FExpressionInput Exponent;
    //## END PROPS MaterialExpressionPower

    DECLARE_CLASS(UMaterialExpressionPower,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionReflectionVector : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionReflectionVector
    //## END PROPS MaterialExpressionReflectionVector

    DECLARE_CLASS(UMaterialExpressionReflectionVector,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;
};

class UMaterialExpressionRotator : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionRotator
    FExpressionInput Coordinate;
    FExpressionInput Time;
    FLOAT CenterX;
    FLOAT CenterY;
    FLOAT Speed;
    //## END PROPS MaterialExpressionRotator

    DECLARE_CLASS(UMaterialExpressionRotator,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionScalarParameter : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionScalarParameter
    FName ParameterName;
    FLOAT DefaultValue;
    //## END PROPS MaterialExpressionScalarParameter

    DECLARE_CLASS(UMaterialExpressionScalarParameter,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;
};

class UMaterialExpressionSceneDepth : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionSceneDepth
    FExpressionInput Coordinates;
    BITFIELD bNormalize:1;
    //## END PROPS MaterialExpressionSceneDepth

    DECLARE_CLASS(UMaterialExpressionSceneDepth,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );

	virtual FString GetCaption() const;
};

class UMaterialExpressionSceneTexture : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionSceneTexture
    FExpressionInput Coordinates;
    BYTE SceneTextureType;
    //## END PROPS MaterialExpressionSceneTexture

    DECLARE_CLASS(UMaterialExpressionSceneTexture,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );

	virtual FString GetCaption() const;
};

class UMaterialExpressionScreenPosition : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionScreenPosition
    BITFIELD ScreenAlign:1;
    //## END PROPS MaterialExpressionScreenPosition

    DECLARE_CLASS(UMaterialExpressionScreenPosition,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;
};

class UMaterialExpressionSine : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionSine
    FExpressionInput Input;
    FLOAT Period;
    //## END PROPS MaterialExpressionSine

    DECLARE_CLASS(UMaterialExpressionSine,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionSquareRoot : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionSquareRoot
    FExpressionInput Input;
    //## END PROPS MaterialExpressionSquareRoot

    DECLARE_CLASS(UMaterialExpressionSquareRoot,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionSubtract : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionSubtract
    FExpressionInput A;
    FExpressionInput B;
    //## END PROPS MaterialExpressionSubtract

    DECLARE_CLASS(UMaterialExpressionSubtract,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionTextureCoordinate : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionTextureCoordinate
    INT CoordinateIndex;
    FLOAT Tiling;
    //## END PROPS MaterialExpressionTextureCoordinate

    DECLARE_CLASS(UMaterialExpressionTextureCoordinate,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;
};

class UMaterialExpressionTextureSample : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionTextureSample
    class UTexture* Texture;
    FExpressionInput Coordinates;
    //## END PROPS MaterialExpressionTextureSample

    DECLARE_CLASS(UMaterialExpressionTextureSample,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;
	virtual INT GetWidth() const;
	virtual FString GetCaption() const;
	virtual INT GetLabelPadding() { return 8; }

	/**
	 * Updates the material's cached reference to the resource for a given texture.
	 * @param Texture - The UTexture which has a new FTexture.
	 */
	void UpdateTextureResource(class UTexture* Texture);

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionDepthBiasBlend : public UMaterialExpressionTextureSample
{
public:
    //## BEGIN PROPS MaterialExpressionDepthBiasBlend
    BITFIELD bNormalize:1;
    FLOAT BiasScale;
    FExpressionInput Bias;
    //## END PROPS MaterialExpressionDepthBiasBlend

    DECLARE_CLASS(UMaterialExpressionDepthBiasBlend,UMaterialExpressionTextureSample,0,Engine)
	/**
	 *	Compile the material expression
	 *
	 *	@param	Compiler	Pointer to the material compiler to use
	 *
	 *	@return	INT			The compiled code index
	 */	
	virtual INT Compile(FMaterialCompiler* Compiler);

	/**
	 *	Get the outputs associated with the expression
	 *
	 *	@param	Outputs		The array that contains the output expression
	 */	
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;

	/**
	 */	
	virtual INT GetWidth() const;

	/**
	 */	
	virtual FString GetCaption() const;

	/**
	 */	
	virtual INT GetLabelPadding() { return 8; }

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionFlipBookSample : public UMaterialExpressionTextureSample
{
public:
    //## BEGIN PROPS MaterialExpressionFlipBookSample
    //## END PROPS MaterialExpressionFlipBookSample

    DECLARE_CLASS(UMaterialExpressionFlipBookSample,UMaterialExpressionTextureSample,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;
};

class UMaterialExpressionMeshSubUV : public UMaterialExpressionTextureSample
{
public:
    //## BEGIN PROPS MaterialExpressionMeshSubUV
    //## END PROPS MaterialExpressionMeshSubUV

    DECLARE_CLASS(UMaterialExpressionMeshSubUV,UMaterialExpressionTextureSample,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;
	virtual INT GetWidth() const;
	virtual FString GetCaption() const;
	virtual INT GetLabelPadding() { return 8; }
};

class UMaterialExpressionParticleSubUV : public UMaterialExpressionTextureSample
{
public:
    //## BEGIN PROPS MaterialExpressionParticleSubUV
    //## END PROPS MaterialExpressionParticleSubUV

    DECLARE_CLASS(UMaterialExpressionParticleSubUV,UMaterialExpressionTextureSample,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;
	virtual INT GetWidth() const;
	virtual FString GetCaption() const;
	virtual INT GetLabelPadding() { return 8; }
};

class UMaterialExpressionTextureSampleParameter : public UMaterialExpressionTextureSample
{
public:
    //## BEGIN PROPS MaterialExpressionTextureSampleParameter
    FName ParameterName;
    //## END PROPS MaterialExpressionTextureSampleParameter

    DECLARE_ABSTRACT_CLASS(UMaterialExpressionTextureSampleParameter,UMaterialExpressionTextureSample,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	virtual UBOOL TextureIsValid( UTexture* InTexture );
	virtual const TCHAR* GetRequirements();
	
	/**
	 *	Sets the default texture if none is set
	 */
	virtual void SetDefaultTexture();
};

class UMaterialExpressionTextureSampleParameter2D : public UMaterialExpressionTextureSampleParameter
{
public:
    //## BEGIN PROPS MaterialExpressionTextureSampleParameter2D
    //## END PROPS MaterialExpressionTextureSampleParameter2D

    DECLARE_CLASS(UMaterialExpressionTextureSampleParameter2D,UMaterialExpressionTextureSampleParameter,0,Engine)
	virtual FString GetCaption() const;
	virtual UBOOL TextureIsValid( UTexture* InTexture );
	virtual const TCHAR* GetRequirements();
	
	/**
	 *	Sets the default texture if none is set
	 */
	virtual void SetDefaultTexture();
};

class UMaterialExpressionTextureSampleParameterCube : public UMaterialExpressionTextureSampleParameter
{
public:
    //## BEGIN PROPS MaterialExpressionTextureSampleParameterCube
    //## END PROPS MaterialExpressionTextureSampleParameterCube

    DECLARE_CLASS(UMaterialExpressionTextureSampleParameterCube,UMaterialExpressionTextureSampleParameter,0,Engine)
	virtual FString GetCaption() const;
	virtual UBOOL TextureIsValid( UTexture* InTexture );
	virtual const TCHAR* GetRequirements();
	
	/**
	 *	Sets the default texture if none is set
	 */
	virtual void SetDefaultTexture();
};

class UMaterialExpressionTextureSampleParameterMovie : public UMaterialExpressionTextureSampleParameter
{
public:
    //## BEGIN PROPS MaterialExpressionTextureSampleParameterMovie
    //## END PROPS MaterialExpressionTextureSampleParameterMovie

    DECLARE_CLASS(UMaterialExpressionTextureSampleParameterMovie,UMaterialExpressionTextureSampleParameter,0,Engine)
	/**
	 * Textual description for this material expression
	 *
	 * @return	Caption text
	 */	
	virtual FString GetCaption() const;

	/**
	 * Return true if the texture is a movie texture
	 *
	 * @param	InTexture - texture to test
	 * @return	true/false
	 */	
	virtual UBOOL TextureIsValid( UTexture* InTexture );

    /**
	 * Called when TextureIsValid==false
	 *
	 * @return	Descriptive error text
	 */	
	virtual const TCHAR* GetRequirements();
};

class UMaterialExpressionTime : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionTime
    BITFIELD bIgnorePause:1;
    //## END PROPS MaterialExpressionTime

    DECLARE_CLASS(UMaterialExpressionTime,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;
};

class UMaterialExpressionTransform : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionTransform
    FExpressionInput Input;
    BYTE TransformType;
    //## END PROPS MaterialExpressionTransform

    DECLARE_CLASS(UMaterialExpressionTransform,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionUserTransform : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionUserTransform
    FExpressionInput Coordinate;
    FExpressionInput RowX;
    FExpressionInput RowY;
    FExpressionInput Translation;
    FExpressionInput Scaling;
    //## END PROPS MaterialExpressionUserTransform

    DECLARE_CLASS(UMaterialExpressionUserTransform,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;

	/**
	 * Removes references to the passed in expression.
	 *
	 * @param	Expression		Expression to remove reference to
	 */
	virtual void RemoveReferenceTo( UMaterialExpression* Expression );
};

class UMaterialExpressionVectorParameter : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionVectorParameter
    FName ParameterName;
    FLinearColor DefaultValue;
    //## END PROPS MaterialExpressionVectorParameter

    DECLARE_CLASS(UMaterialExpressionVectorParameter,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;
	virtual FString GetCaption() const;
};

class UMaterialExpressionVertexColor : public UMaterialExpression
{
public:
    //## BEGIN PROPS MaterialExpressionVertexColor
    //## END PROPS MaterialExpressionVertexColor

    DECLARE_CLASS(UMaterialExpressionVertexColor,UMaterialExpression,0,Engine)
	virtual INT Compile(FMaterialCompiler* Compiler);
	virtual FString GetCaption() const;
	virtual void GetOutputs(TArray<FExpressionOutput>& Outputs) const;
};

struct FVectorParameterValue
{
    FName ParameterName;
    FLinearColor ParameterValue;
};

struct FScalarParameterValue
{
    FName ParameterName;
    FLOAT ParameterValue;
};

struct FTextureParameterValue
{
    FName ParameterName;
    class UTexture* ParameterValue;
    INT PlatformDependency;
};

class UMaterialInstanceConstant : public UMaterialInstance
{
public:
    //## BEGIN PROPS MaterialInstanceConstant
    class UPhysicalMaterial* PhysMaterial;
    class UMaterialInstance* Parent;
    TArrayNoInit<struct FVectorParameterValue> VectorParameterValues;
    TArrayNoInit<struct FScalarParameterValue> ScalarParameterValues;
    TArrayNoInit<struct FTextureParameterValue> TextureParameterValues;
    TArrayNoInit<struct FTextureParameterValue> NewTextureParameterValues;
    class FMaterialInstanceResource* Resources[2];
    BITFIELD ReentrantFlag:1;
    BITFIELD bPlatformDependencyDirty:1;
    //## END PROPS MaterialInstanceConstant

    void SetParent(class UMaterialInstance* NewParent);
    void SetVectorParameterValue(FName ParameterName,FLinearColor Value);
    void SetScalarParameterValue(FName ParameterName,FLOAT Value);
    void SetTextureParameterValue(FName ParameterName,class UTexture* Value);
    void ClearParameterValues();
    DECLARE_FUNCTION(execSetParent)
    {
        P_GET_OBJECT(UMaterialInstance,NewParent);
        P_FINISH;
        SetParent(NewParent);
    }
    DECLARE_FUNCTION(execSetVectorParameterValue)
    {
        P_GET_NAME(ParameterName);
        P_GET_STRUCT(FLinearColor,Value);
        P_FINISH;
        SetVectorParameterValue(ParameterName,Value);
    }
    DECLARE_FUNCTION(execSetScalarParameterValue)
    {
        P_GET_NAME(ParameterName);
        P_GET_FLOAT(Value);
        P_FINISH;
        SetScalarParameterValue(ParameterName,Value);
    }
    DECLARE_FUNCTION(execSetTextureParameterValue)
    {
        P_GET_NAME(ParameterName);
        P_GET_OBJECT(UTexture,Value);
        P_FINISH;
        SetTextureParameterValue(ParameterName,Value);
    }
    DECLARE_FUNCTION(execClearParameterValues)
    {
        P_FINISH;
        ClearParameterValues();
    }
    DECLARE_CLASS(UMaterialInstanceConstant,UMaterialInstance,0,Engine)
	// Constructor.
	UMaterialInstanceConstant();

	// UMaterialInstance interface.
	virtual UMaterial* GetMaterial();
    virtual UBOOL GetVectorParameterValue(FName ParameterName,FLinearColor& OutValue);
    virtual UBOOL GetScalarParameterValue(FName ParameterName,FLOAT& OutValue);
    virtual UBOOL GetTextureParameterValue(FName ParameterName,class UTexture*& OutValue);
	virtual UBOOL IsDependent(UMaterialInstance* TestDependency);
	virtual FMaterialInstance* GetInstanceInterface(UBOOL Selected) const;
	virtual UPhysicalMaterial* GetPhysicalMaterial();

	// UObject interface.
	virtual void PostLoad();
	virtual void PostEditChange(UProperty* PropertyThatChanged);
	virtual void FinishDestroy();
	virtual void Serialize(FArchive& Ar);

	void DeterminePlatformTextureDependencies();
};

#endif

AUTOGENERATE_FUNCTION(UMaterialInstanceConstant,-1,execClearParameterValues);
AUTOGENERATE_FUNCTION(UMaterialInstanceConstant,-1,execSetTextureParameterValue);
AUTOGENERATE_FUNCTION(UMaterialInstanceConstant,-1,execSetScalarParameterValue);
AUTOGENERATE_FUNCTION(UMaterialInstanceConstant,-1,execSetVectorParameterValue);
AUTOGENERATE_FUNCTION(UMaterialInstanceConstant,-1,execSetParent);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef ENGINE_MATERIAL_NATIVE_DEFS
#define ENGINE_MATERIAL_NATIVE_DEFS

DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionAbs);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionAdd);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionAppendVector);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionBumpOffset);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionCameraVector);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionCeil);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionClamp);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionComment);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionComponentMask);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionCompound);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionConstant);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionConstant2Vector);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionConstant3Vector);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionConstant4Vector);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionCosine);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionCrossProduct);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionDepthBiasBlend);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionDepthBiasedAlpha);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionDepthBiasedBlend);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionDesaturation);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionDestColor);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionDestDepth);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionDivide);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionDotProduct);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionEnvCube);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionFallback);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionFlipBookSample);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionFloor);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionFrac);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionFresnel);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionIf);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionLensFlareIntensity);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionLensFlareRadialDistance);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionLensFlareRayDistance);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionLensFlareSourceDistance);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionLightVector);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionLinearInterpolate);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionMeshEmitterVertexColor);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionMeshSubUV);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionMultiply);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionNormalize);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionOneMinus);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionPanner);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionParticleSubUV);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionPixelDepth);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionPower);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionReflectionVector);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionRotator);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionScalarParameter);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionSceneDepth);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionSceneTexture);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionScreenPosition);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionSine);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionSquareRoot);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionSubtract);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionTextureCoordinate);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionTextureSample);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionTextureSampleParameter);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionTextureSampleParameter2D);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionTextureSampleParameterCube);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionTextureSampleParameterMovie);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionTime);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionTransform);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionUserTransform);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionVectorParameter);
DECLARE_NATIVE_TYPE(Engine,UMaterialExpressionVertexColor);
DECLARE_NATIVE_TYPE(Engine,UMaterialInstanceConstant);

#define AUTO_INITIALIZE_REGISTRANTS_ENGINE_MATERIAL \
	UMaterialExpressionAbs::StaticClass(); \
	UMaterialExpressionAdd::StaticClass(); \
	UMaterialExpressionAppendVector::StaticClass(); \
	UMaterialExpressionBumpOffset::StaticClass(); \
	UMaterialExpressionCameraVector::StaticClass(); \
	UMaterialExpressionCeil::StaticClass(); \
	UMaterialExpressionClamp::StaticClass(); \
	UMaterialExpressionComment::StaticClass(); \
	UMaterialExpressionComponentMask::StaticClass(); \
	UMaterialExpressionCompound::StaticClass(); \
	UMaterialExpressionConstant::StaticClass(); \
	UMaterialExpressionConstant2Vector::StaticClass(); \
	UMaterialExpressionConstant3Vector::StaticClass(); \
	UMaterialExpressionConstant4Vector::StaticClass(); \
	UMaterialExpressionCosine::StaticClass(); \
	UMaterialExpressionCrossProduct::StaticClass(); \
	UMaterialExpressionDepthBiasBlend::StaticClass(); \
	UMaterialExpressionDepthBiasedAlpha::StaticClass(); \
	UMaterialExpressionDepthBiasedBlend::StaticClass(); \
	UMaterialExpressionDesaturation::StaticClass(); \
	UMaterialExpressionDestColor::StaticClass(); \
	UMaterialExpressionDestDepth::StaticClass(); \
	UMaterialExpressionDivide::StaticClass(); \
	UMaterialExpressionDotProduct::StaticClass(); \
	UMaterialExpressionEnvCube::StaticClass(); \
	UMaterialExpressionFallback::StaticClass(); \
	UMaterialExpressionFlipBookSample::StaticClass(); \
	UMaterialExpressionFloor::StaticClass(); \
	UMaterialExpressionFrac::StaticClass(); \
	UMaterialExpressionFresnel::StaticClass(); \
	UMaterialExpressionIf::StaticClass(); \
	UMaterialExpressionLensFlareIntensity::StaticClass(); \
	UMaterialExpressionLensFlareRadialDistance::StaticClass(); \
	UMaterialExpressionLensFlareRayDistance::StaticClass(); \
	UMaterialExpressionLensFlareSourceDistance::StaticClass(); \
	UMaterialExpressionLightVector::StaticClass(); \
	UMaterialExpressionLinearInterpolate::StaticClass(); \
	UMaterialExpressionMeshEmitterVertexColor::StaticClass(); \
	UMaterialExpressionMeshSubUV::StaticClass(); \
	UMaterialExpressionMultiply::StaticClass(); \
	UMaterialExpressionNormalize::StaticClass(); \
	UMaterialExpressionOneMinus::StaticClass(); \
	UMaterialExpressionPanner::StaticClass(); \
	UMaterialExpressionParticleSubUV::StaticClass(); \
	UMaterialExpressionPixelDepth::StaticClass(); \
	UMaterialExpressionPower::StaticClass(); \
	UMaterialExpressionReflectionVector::StaticClass(); \
	UMaterialExpressionRotator::StaticClass(); \
	UMaterialExpressionScalarParameter::StaticClass(); \
	UMaterialExpressionSceneDepth::StaticClass(); \
	UMaterialExpressionSceneTexture::StaticClass(); \
	UMaterialExpressionScreenPosition::StaticClass(); \
	UMaterialExpressionSine::StaticClass(); \
	UMaterialExpressionSquareRoot::StaticClass(); \
	UMaterialExpressionSubtract::StaticClass(); \
	UMaterialExpressionTextureCoordinate::StaticClass(); \
	UMaterialExpressionTextureSample::StaticClass(); \
	UMaterialExpressionTextureSampleParameter::StaticClass(); \
	UMaterialExpressionTextureSampleParameter2D::StaticClass(); \
	UMaterialExpressionTextureSampleParameterCube::StaticClass(); \
	UMaterialExpressionTextureSampleParameterMovie::StaticClass(); \
	UMaterialExpressionTime::StaticClass(); \
	UMaterialExpressionTransform::StaticClass(); \
	UMaterialExpressionUserTransform::StaticClass(); \
	UMaterialExpressionVectorParameter::StaticClass(); \
	UMaterialExpressionVertexColor::StaticClass(); \
	UMaterialInstanceConstant::StaticClass(); \
	GNativeLookupFuncs[Lookup++] = &FindEngineUMaterialInstanceConstantNative; \

#endif // ENGINE_MATERIAL_NATIVE_DEFS

#ifdef NATIVES_ONLY
NATIVE_INFO(UMaterialInstanceConstant) GEngineUMaterialInstanceConstantNatives[] = 
{ 
	MAP_NATIVE(UMaterialInstanceConstant,execClearParameterValues)
	MAP_NATIVE(UMaterialInstanceConstant,execSetTextureParameterValue)
	MAP_NATIVE(UMaterialInstanceConstant,execSetScalarParameterValue)
	MAP_NATIVE(UMaterialInstanceConstant,execSetVectorParameterValue)
	MAP_NATIVE(UMaterialInstanceConstant,execSetParent)
	{NULL,NULL}
};
IMPLEMENT_NATIVE_HANDLER(Engine,UMaterialInstanceConstant);

#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionAbs,Input)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionAbs)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionAdd,A)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionAdd,B)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionAdd)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionAppendVector,A)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionAppendVector,B)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionAppendVector)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionBumpOffset,Coordinate)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionBumpOffset,ReferencePlane)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionBumpOffset)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionCameraVector)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionCeil,Input)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionCeil)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionClamp,Input)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionClamp,Max)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionClamp)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionComment,PosX)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionComment,Text)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionComment)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionComponentMask,Input)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionComponentMask)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionCompound,MaterialExpressions)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionCompound,Caption)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionCompound)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionConstant,R)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionConstant)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionConstant2Vector,R)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionConstant2Vector,G)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionConstant2Vector)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionConstant3Vector,R)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionConstant3Vector,B)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionConstant3Vector)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionConstant4Vector,R)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionConstant4Vector,A)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionConstant4Vector)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionCosine,Input)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionCosine,Period)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionCosine)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionCrossProduct,A)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionCrossProduct,B)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionCrossProduct)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionDepthBiasBlend,BiasScale)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionDepthBiasBlend,Bias)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionDepthBiasBlend)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionDepthBiasedAlpha,BiasScale)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionDepthBiasedAlpha,Bias)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionDepthBiasedAlpha)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionDepthBiasedBlend,BiasScale)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionDepthBiasedBlend,Bias)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionDepthBiasedBlend)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionDesaturation,Input)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionDesaturation,LuminanceFactors)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionDesaturation)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionDestColor)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionDestDepth)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionDivide,A)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionDivide,B)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionDivide)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionDotProduct,A)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionDotProduct,B)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionDotProduct)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionEnvCube,Coordinates)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionEnvCube)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionFallback,PCD3D)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionFallback,DefaultCase)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionFallback)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionFlipBookSample)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionFloor,Input)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionFloor)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionFrac,Input)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionFrac)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionFresnel,Exponent)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionFresnel,Normal)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionFresnel)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionIf,A)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionIf,ALessThanB)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionIf)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionLensFlareIntensity)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionLensFlareRadialDistance)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionLensFlareRayDistance)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionLensFlareSourceDistance)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionLightVector)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionLinearInterpolate,A)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionLinearInterpolate,Alpha)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionLinearInterpolate)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionMeshEmitterVertexColor)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionMeshSubUV)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionMultiply,A)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionMultiply,B)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionMultiply)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionNormalize,VectorInput)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionNormalize)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionOneMinus,Input)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionOneMinus)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionPanner,Coordinate)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionPanner,SpeedY)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionPanner)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionParticleSubUV)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionPixelDepth)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionPower,Base)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionPower,Exponent)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionPower)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionReflectionVector)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionRotator,Coordinate)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionRotator,Speed)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionRotator)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionScalarParameter,ParameterName)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionScalarParameter,DefaultValue)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionScalarParameter)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionSceneDepth,Coordinates)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionSceneDepth)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionSceneTexture,Coordinates)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionSceneTexture,SceneTextureType)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionSceneTexture)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionScreenPosition)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionSine,Input)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionSine,Period)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionSine)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionSquareRoot,Input)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionSquareRoot)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionSubtract,A)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionSubtract,B)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionSubtract)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionTextureCoordinate,CoordinateIndex)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionTextureCoordinate,Tiling)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionTextureCoordinate)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionTextureSample,Texture)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionTextureSample,Coordinates)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionTextureSample)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionTextureSampleParameter,ParameterName)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionTextureSampleParameter)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionTextureSampleParameter2D)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionTextureSampleParameterCube)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionTextureSampleParameterMovie)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionTime)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionTransform,Input)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionTransform,TransformType)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionTransform)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionUserTransform,Coordinate)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionUserTransform,Scaling)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionUserTransform)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionVectorParameter,ParameterName)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialExpressionVectorParameter,DefaultValue)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionVectorParameter)
VERIFY_CLASS_SIZE_NODIE(UMaterialExpressionVertexColor)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialInstanceConstant,PhysMaterial)
VERIFY_CLASS_OFFSET_NODIE(U,MaterialInstanceConstant,Resources)
VERIFY_CLASS_SIZE_NODIE(UMaterialInstanceConstant)
#endif // VERIFY_CLASS_SIZES
#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
