/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif


// Split enums from the rest of the header so they can be included earlier
// than the rest of the header file by including this file twice with different
// #define wrappers. See Engine.h and look at EngineClasses.h for an example.
#if !NO_ENUMS && !defined(NAMES_ONLY)


#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern FName GAMEFRAMEWORK_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

class AGamePawn : public APawn
{
public:
    //## BEGIN PROPS GamePawn
    //## END PROPS GamePawn

    DECLARE_ABSTRACT_CLASS(AGamePawn,APawn,0|CLASS_Config,GameFramework)
    NO_DEFAULT_CONSTRUCTOR(AGamePawn)
};

class AGamePlayerController : public APlayerController
{
public:
    //## BEGIN PROPS GamePlayerController
    //## END PROPS GamePlayerController

    DECLARE_CLASS(AGamePlayerController,APlayerController,0|CLASS_Config,GameFramework)
    NO_DEFAULT_CONSTRUCTOR(AGamePlayerController)
};

#endif


#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef GAMEFRAMEWORK_NATIVE_DEFS
#define GAMEFRAMEWORK_NATIVE_DEFS

DECLARE_NATIVE_TYPE(GameFramework,AGamePawn);
DECLARE_NATIVE_TYPE(GameFramework,AGamePlayerController);

#define AUTO_INITIALIZE_REGISTRANTS_GAMEFRAMEWORK \
	AGamePawn::StaticClass(); \
	AGamePlayerController::StaticClass(); \

#endif // GAMEFRAMEWORK_NATIVE_DEFS

#ifdef NATIVES_ONLY
#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(AGamePawn)
VERIFY_CLASS_SIZE_NODIE(AGamePlayerController)
#endif // VERIFY_CLASS_SIZES
#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
