/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif


// Split enums from the rest of the header so they can be included earlier
// than the rest of the header file by including this file twice with different
// #define wrappers. See Engine.h and look at EngineClasses.h for an example.
#if !NO_ENUMS && !defined(NAMES_ONLY)


#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern FName ONLINESUBSYSTEMPC_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(OnArbitrationRegistrationComplete)
AUTOGENERATE_NAME(OnCreateOnlineGameComplete)
AUTOGENERATE_NAME(OnDestroyOnlineGameComplete)
AUTOGENERATE_NAME(OnEndOnlineGameComplete)
AUTOGENERATE_NAME(OnFindOnlineGamesComplete)
AUTOGENERATE_NAME(OnFlushOnlineStatsComplete)
AUTOGENERATE_NAME(OnFriendsChange)
AUTOGENERATE_NAME(OnGameInviteAccepted)
AUTOGENERATE_NAME(OnJoinOnlineGameComplete)
AUTOGENERATE_NAME(OnKeyboardInputComplete)
AUTOGENERATE_NAME(OnLoginCancelled)
AUTOGENERATE_NAME(OnLoginChange)
AUTOGENERATE_NAME(OnMutingChange)
AUTOGENERATE_NAME(OnPlayerTalking)
AUTOGENERATE_NAME(OnReadFriendsComplete)
AUTOGENERATE_NAME(OnReadOnlineStatsComplete)
AUTOGENERATE_NAME(OnReadProfileSettingsComplete)
AUTOGENERATE_NAME(OnRecognitionComplete)
AUTOGENERATE_NAME(OnRegisterPlayerComplete)
AUTOGENERATE_NAME(OnStartOnlineGameComplete)
AUTOGENERATE_NAME(OnUnregisterPlayerComplete)
AUTOGENERATE_NAME(OnWriteProfileSettingsComplete)

#ifndef NAMES_ONLY

struct OnlineSubsystemPC_eventOnFlushOnlineStatsComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnFlushOnlineStatsComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnReadOnlineStatsComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnReadOnlineStatsComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnGameInviteAccepted_Parms
{
    class UOnlineGameSettings* GameInviteSettings;
    OnlineSubsystemPC_eventOnGameInviteAccepted_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnArbitrationRegistrationComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnArbitrationRegistrationComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnEndOnlineGameComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnEndOnlineGameComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnStartOnlineGameComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnStartOnlineGameComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnUnregisterPlayerComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnUnregisterPlayerComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnRegisterPlayerComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnRegisterPlayerComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnJoinOnlineGameComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnJoinOnlineGameComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnFindOnlineGamesComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnFindOnlineGamesComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnDestroyOnlineGameComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnDestroyOnlineGameComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnCreateOnlineGameComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnCreateOnlineGameComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnRecognitionComplete_Parms
{
    OnlineSubsystemPC_eventOnRecognitionComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnPlayerTalking_Parms
{
    struct FUniqueNetId Player;
    OnlineSubsystemPC_eventOnPlayerTalking_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnReadFriendsComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnReadFriendsComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnWriteProfileSettingsComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnWriteProfileSettingsComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnReadProfileSettingsComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnReadProfileSettingsComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnKeyboardInputComplete_Parms
{
    UBOOL bWasSuccessful;
    OnlineSubsystemPC_eventOnKeyboardInputComplete_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnFriendsChange_Parms
{
    OnlineSubsystemPC_eventOnFriendsChange_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnMutingChange_Parms
{
    OnlineSubsystemPC_eventOnMutingChange_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnLoginCancelled_Parms
{
    OnlineSubsystemPC_eventOnLoginCancelled_Parms(EEventParm)
    {
    }
};
struct OnlineSubsystemPC_eventOnLoginChange_Parms
{
    OnlineSubsystemPC_eventOnLoginChange_Parms(EEventParm)
    {
    }
};
class UOnlineSubsystemPC : public UOnlineSubsystem
{
public:
    //## BEGIN PROPS OnlineSubsystemPC
    FScriptDelegate __OnLoginChange__Delegate;
    FScriptDelegate __OnLoginCancelled__Delegate;
    FScriptDelegate __OnMutingChange__Delegate;
    FScriptDelegate __OnFriendsChange__Delegate;
    FScriptDelegate __OnKeyboardInputComplete__Delegate;
    FScriptDelegate __OnReadProfileSettingsComplete__Delegate;
    FScriptDelegate __OnWriteProfileSettingsComplete__Delegate;
    FScriptDelegate __OnReadFriendsComplete__Delegate;
    FScriptDelegate __OnPlayerTalking__Delegate;
    FScriptDelegate __OnRecognitionComplete__Delegate;
    FScriptDelegate __OnCreateOnlineGameComplete__Delegate;
    FScriptDelegate __OnDestroyOnlineGameComplete__Delegate;
    FScriptDelegate __OnFindOnlineGamesComplete__Delegate;
    FScriptDelegate __OnJoinOnlineGameComplete__Delegate;
    FScriptDelegate __OnRegisterPlayerComplete__Delegate;
    FScriptDelegate __OnUnregisterPlayerComplete__Delegate;
    FScriptDelegate __OnStartOnlineGameComplete__Delegate;
    FScriptDelegate __OnEndOnlineGameComplete__Delegate;
    FScriptDelegate __OnArbitrationRegistrationComplete__Delegate;
    FScriptDelegate __OnGameInviteAccepted__Delegate;
    FScriptDelegate __OnReadOnlineStatsComplete__Delegate;
    FScriptDelegate __OnFlushOnlineStatsComplete__Delegate;
    //## END PROPS OnlineSubsystemPC

    void delegateOnFlushOnlineStatsComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnFlushOnlineStatsComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnFlushOnlineStatsComplete,&__OnFlushOnlineStatsComplete__Delegate,&Parms);
    }
    void delegateOnReadOnlineStatsComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnReadOnlineStatsComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnReadOnlineStatsComplete,&__OnReadOnlineStatsComplete__Delegate,&Parms);
    }
    void delegateOnGameInviteAccepted(class UOnlineGameSettings* GameInviteSettings)
    {
        OnlineSubsystemPC_eventOnGameInviteAccepted_Parms Parms(EC_EventParm);
        Parms.GameInviteSettings=GameInviteSettings;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnGameInviteAccepted,&__OnGameInviteAccepted__Delegate,&Parms);
    }
    void delegateOnArbitrationRegistrationComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnArbitrationRegistrationComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnArbitrationRegistrationComplete,&__OnArbitrationRegistrationComplete__Delegate,&Parms);
    }
    void delegateOnEndOnlineGameComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnEndOnlineGameComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnEndOnlineGameComplete,&__OnEndOnlineGameComplete__Delegate,&Parms);
    }
    void delegateOnStartOnlineGameComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnStartOnlineGameComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnStartOnlineGameComplete,&__OnStartOnlineGameComplete__Delegate,&Parms);
    }
    void delegateOnUnregisterPlayerComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnUnregisterPlayerComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnUnregisterPlayerComplete,&__OnUnregisterPlayerComplete__Delegate,&Parms);
    }
    void delegateOnRegisterPlayerComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnRegisterPlayerComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnRegisterPlayerComplete,&__OnRegisterPlayerComplete__Delegate,&Parms);
    }
    void delegateOnJoinOnlineGameComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnJoinOnlineGameComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnJoinOnlineGameComplete,&__OnJoinOnlineGameComplete__Delegate,&Parms);
    }
    void delegateOnFindOnlineGamesComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnFindOnlineGamesComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnFindOnlineGamesComplete,&__OnFindOnlineGamesComplete__Delegate,&Parms);
    }
    void delegateOnDestroyOnlineGameComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnDestroyOnlineGameComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnDestroyOnlineGameComplete,&__OnDestroyOnlineGameComplete__Delegate,&Parms);
    }
    void delegateOnCreateOnlineGameComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnCreateOnlineGameComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnCreateOnlineGameComplete,&__OnCreateOnlineGameComplete__Delegate,&Parms);
    }
    void delegateOnRecognitionComplete()
    {
        ProcessDelegate(ONLINESUBSYSTEMPC_OnRecognitionComplete,&__OnRecognitionComplete__Delegate,NULL);
    }
    void delegateOnPlayerTalking(struct FUniqueNetId Player)
    {
        OnlineSubsystemPC_eventOnPlayerTalking_Parms Parms(EC_EventParm);
        Parms.Player=Player;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnPlayerTalking,&__OnPlayerTalking__Delegate,&Parms);
    }
    void delegateOnReadFriendsComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnReadFriendsComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnReadFriendsComplete,&__OnReadFriendsComplete__Delegate,&Parms);
    }
    void delegateOnWriteProfileSettingsComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnWriteProfileSettingsComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnWriteProfileSettingsComplete,&__OnWriteProfileSettingsComplete__Delegate,&Parms);
    }
    void delegateOnReadProfileSettingsComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnReadProfileSettingsComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnReadProfileSettingsComplete,&__OnReadProfileSettingsComplete__Delegate,&Parms);
    }
    void delegateOnKeyboardInputComplete(UBOOL bWasSuccessful)
    {
        OnlineSubsystemPC_eventOnKeyboardInputComplete_Parms Parms(EC_EventParm);
        Parms.bWasSuccessful=bWasSuccessful ? FIRST_BITFIELD : 0;
        ProcessDelegate(ONLINESUBSYSTEMPC_OnKeyboardInputComplete,&__OnKeyboardInputComplete__Delegate,&Parms);
    }
    void delegateOnFriendsChange()
    {
        ProcessDelegate(ONLINESUBSYSTEMPC_OnFriendsChange,&__OnFriendsChange__Delegate,NULL);
    }
    void delegateOnMutingChange()
    {
        ProcessDelegate(ONLINESUBSYSTEMPC_OnMutingChange,&__OnMutingChange__Delegate,NULL);
    }
    void delegateOnLoginCancelled()
    {
        ProcessDelegate(ONLINESUBSYSTEMPC_OnLoginCancelled,&__OnLoginCancelled__Delegate,NULL);
    }
    void delegateOnLoginChange()
    {
        ProcessDelegate(ONLINESUBSYSTEMPC_OnLoginChange,&__OnLoginChange__Delegate,NULL);
    }
    DECLARE_CLASS(UOnlineSubsystemPC,UOnlineSubsystem,0,OnlineSubsystemPC)
    static const TCHAR* StaticConfigName() {return TEXT("Engine");}

    NO_DEFAULT_CONSTRUCTOR(UOnlineSubsystemPC)
};

#endif


#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef ONLINESUBSYSTEMPC_NATIVE_DEFS
#define ONLINESUBSYSTEMPC_NATIVE_DEFS

DECLARE_NATIVE_TYPE(OnlineSubsystemPC,UOnlineSubsystemPC);

#define AUTO_INITIALIZE_REGISTRANTS_ONLINESUBSYSTEMPC \
	UOnlineSubsystemPC::StaticClass(); \

#endif // ONLINESUBSYSTEMPC_NATIVE_DEFS

#ifdef NATIVES_ONLY
#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE(U,OnlineSubsystemPC,__OnLoginChange__Delegate)
VERIFY_CLASS_OFFSET_NODIE(U,OnlineSubsystemPC,__OnFlushOnlineStatsComplete__Delegate)
VERIFY_CLASS_SIZE_NODIE(UOnlineSubsystemPC)
#endif // VERIFY_CLASS_SIZES
#endif // !ENUMS_ONLY
