/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif


// Split enums from the rest of the header so they can be included earlier
// than the rest of the header file by including this file twice with different
// #define wrappers. See Engine.h and look at EngineClasses.h for an example.
#if !NO_ENUMS && !defined(NAMES_ONLY)


#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern FName AVANET_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

class UavaSeqAction : public USequenceAction
{
public:
    //## BEGIN PROPS avaSeqAction
    //## END PROPS avaSeqAction

    DECLARE_ABSTRACT_CLASS(UavaSeqAction,USequenceAction,0,avaNet)
    NO_DEFAULT_CONSTRUCTOR(UavaSeqAction)
};

#endif


#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef AVANET_SEQUENCE_NATIVE_DEFS
#define AVANET_SEQUENCE_NATIVE_DEFS

DECLARE_NATIVE_TYPE(avaNet,UavaSeqAction);

#define AUTO_INITIALIZE_REGISTRANTS_AVANET_SEQUENCE \
	UavaSeqAction::StaticClass(); \

#endif // AVANET_SEQUENCE_NATIVE_DEFS

#ifdef NATIVES_ONLY
#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(UavaSeqAction)
#endif // VERIFY_CLASS_SIZES
#endif // !ENUMS_ONLY
