/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif


// Split enums from the rest of the header so they can be included earlier
// than the rest of the header file by including this file twice with different
// #define wrappers. See Engine.h and look at EngineClasses.h for an example.
#if !NO_ENUMS && !defined(NAMES_ONLY)

enum ENetMissionType
{
    NMT_Mission             =0,
    NMT_Warfare             =1,
    NMT_MilitaryDrill       =2,
    NMT_MAX                 =3,
};
enum EItemEffectType
{
    IET_None                =0,
    IET_GR                  =1,
    IET_EXP_BOOST           =2,
    IET_SP_BOOST            =3,
    IET_MONEY_BOOST         =4,
    IET_ACCESSORY           =5,
    IET_MAX                 =6,
};
enum EPlayerClass
{
    EClass_Pointman         =0,
    EClass_Rifleman         =1,
    EClass_Sniper           =2,
    EClass_MAX              =3,
};

#endif // !NO_ENUMS

#if !ENUMS_ONLY

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern FName AVANET_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

struct FavaRoomSetting
{
    INT idMap;
    INT tkLevel;
    BITFIELD autoBalance:1;
    BITFIELD allowSpectator:1;
    BITFIELD allowInterrupt:1;
    BITFIELD allowBackView:1;
    BITFIELD allowGameGhostChat:1;
    BITFIELD autoSwapTeam:1;
    INT roundToWin;
    INT MaxPlayer;
    INT mapOption;
    BITFIELD bPassword:1;
};

struct FavaNetChannelInfo
{
    INT idChannel;
    BYTE Flag;
    INT ChIdx;
};

struct FavaNetChannelSettingInfo
{
    BYTE Flag;
    BITFIELD EnableAutoBalance:1 GCC_BITFIELD_MAGIC;
    BITFIELD EnableSpectator:1;
    BITFIELD EnableInterrupt:1;
    BITFIELD EnableBackView:1;
    BITFIELD EnableGhostChat:1;
    BITFIELD EnableAutoSwapTeam:1;
    BITFIELD EnableMaxPlayers:1;
    BITFIELD EnableTKLevel:1;
    BITFIELD MissionTypeSpecial:1;
    BITFIELD MissionTypeWarfare:1;
    BITFIELD MissionTypeTraining:1;
    BITFIELD DefaultAutoBalance:1;
    BITFIELD DefaultSpectator:1;
    BITFIELD DefaultInterrupt:1;
    BITFIELD DefaultBackView:1;
    BITFIELD DefaultGhostChat:1;
    BITFIELD DefaultAutoSwapTeam:1;
    BYTE DefaultTKLevel GCC_BITFIELD_MAGIC;
    BYTE DefaultMaxPlayers;
    BITFIELD RoomChangeTeam:1 GCC_BITFIELD_MAGIC;
    BITFIELD RoomSkipMinPlayerCheck:1;
    BITFIELD RoomSkipBalanceCheck:1;
    BITFIELD GameIdleCheck:1;
    BITFIELD GameFreeCam:1;
    BITFIELD GameCheckAllOut:1;
    BITFIELD UpdatePlayerScore:1;
    BITFIELD UpdateStatLog:1;
    BITFIELD InvenCashItem:1;
    BITFIELD AllowPCBangBonus:1;
    BITFIELD AllowBoostItem:1;
    BITFIELD AllowEventBonus:1;
};

struct FavaNetMapInfo
{
    INT MapID;
    BYTE MissionType;
    FStringNoInit MapName;
    FStringNoInit ImagePathName;
    FStringNoInit Description;
    FStringNoInit MapFileName;
    FStringNoInit MaxPlayers;
    FStringNoInit WinCondition;
    FStringNoInit WinConditionType;
    BITFIELD bRedduckInternalOnly:1;
    TArrayNoInit<BYTE> ExclChannelGroups;
    BITFIELD bStatLog:1;
    BITFIELD AllowMapOption:1;

    /** Constructors */
    FavaNetMapInfo() {}
    FavaNetMapInfo(EEventParm)
    {
        appMemzero(this, sizeof(FavaNetMapInfo));
    }
};

struct FavaNetMissionInfo
{
    BYTE MissionType;
    FStringNoInit MaxPlayers;
    FStringNoInit WinCondition;

    /** Constructors */
    FavaNetMissionInfo() {}
    FavaNetMissionInfo(EEventParm)
    {
        appMemzero(this, sizeof(FavaNetMissionInfo));
    }
};

class UavaNetRequest : public UObject
{
public:
    //## BEGIN PROPS avaNetRequest
    TArrayNoInit<struct FavaNetChannelInfo> ChannelList;
    TArrayNoInit<struct FavaNetChannelSettingInfo> ChannelSettingList;
    TArrayNoInit<struct FavaNetMapInfo> MapList;
    TArrayNoInit<struct FavaNetMissionInfo> MissionList;
private:
    TArrayNoInit<struct FavaRoomSetting> RoomSettingTyped;
public:
    //## END PROPS avaNetRequest

    UBOOL AutoConnect(UBOOL bForce,const FString& USN=TEXT(""),const FString& UserID=TEXT(""),const FString& Key=TEXT(""));
    void CloseConnection(INT ExitCode);
    void CreateCharacter(const FString& NickName,INT FaceIndex);
    void Quit(UBOOL bGraceful=TRUE);
    void ListChannel();
    void JoinChannel(INT ListIndex);
    void JoinChannelByID(INT Id,UBOOL bFollowing=FALSE);
    void QuickJoinChannel(const FString& Flags);
    void LeaveChannel();
    void ListRoom();
    void ListLobbyPlayer();
    void LobbySelectRoom(INT ListIndex);
    void CreateRoom(const FString& RoomName,const FString& RoomPassword,struct FavaRoomSetting Setting);
    UBOOL JoinRoom(INT ListIndex,const FString& RoomPassword);
    UBOOL QuickJoinRoom(INT idMap=0);
    void LeaveRoom(BYTE LeavingReason=0);
    void RoomKickPlayer(const FString& NickName,INT Reason=1);
    void RoomSetting(struct FavaRoomSetting Setting);
    void RoomReady(UBOOL Ready);
    void RoomReadyToggle();
    void RoomChangeTeam(INT idTeam);
    void RoomChangeTeamToggle();
    void RoomChangeSlot(INT Slot);
    void RoomChangeClass(INT idClass);
    void RoomStart();
    void RoomCancelStart();
    void RoomSwapTeam(INT Reason=0);
    void RoomClaimHost();
    void SetMyRttValue(FLOAT RttValue);
    void Chat(const FString& ChatMsg);
    UBOOL ParseChatCommand(const FString& Cmd);
    void FilterChatMsg(FString& ChatMsg);
    void LeaveGame();
    void BuddyListBegin();
    void BuddyListEnd();
    void BuddyAdd(UBOOL bForce,const FString& NickName);
    void BuddyAddAns(UBOOL bAccept,const FString& NickName);
    void BuddyDelete(const FString& NickName);
    void BlockAdd(UBOOL bForce,const FString& NickName);
    void BlockDelete(const FString& NickName);
    void Whisper(const FString& NickName,const FString& ChatMsg);
    void InviteGame(const FString& NickName);
    void InviteGameAns(UBOOL bAccept,const FString& NickName);
    void FollowPlayer(const FString& NickName);
    void SetFollowPlayerPwd(const FString& Password);
    void InviteGuild(const FString& NickName);
    void InviteGuildAns(UBOOL bAccept,const FString& NickName);
    void EnterInven();
    void LeaveInven();
    void InvenSetWeapon(INT EquipSlot,INT InvenSlot);
    void InvenSetEquip(INT EquipSlot,INT InvenSlot);
    void InvenSetCustom(INT InvenSlot,INT CustomIndex,INT OptionIndex=0);
    void InvenSetEffect(INT EquipSlot,INT InvenSlot);
    void InvenUnsetWeapon(INT EquipSlot,INT InvenSlot);
    void InvenUnsetEquip(INT EquipSlot,INT InvenSlot);
    void InvenUnsetCustom(INT InvenSlot,INT CustomSlot);
    void InvenUnsetEffect(INT EquipSlot,INT InvenSlot);
    void InvenRepairWeapon(INT InvenSlot);
    void InvenRepairEquip(INT InvenSlot);
    void InvenConvertRIS(INT InvenSlot);
    UBOOL InvenGetWeaponRefundPrice(INT InvenSlot,INT& Money,INT& Cash);
    UBOOL InvenGetEquipRefundPrice(INT InvenSlot,INT& Money,INT& Cash);
    UBOOL InvenGetCustomRefundPrice(INT InvenSlot,INT CustomSlot,INT& Money,INT& Cash);
    INT GetUsedItemEffect(BYTE ItemEffect);
    void ShopBuyWeapon(INT ListIndex,INT OptionIndex=0);
    void ShopBuyEquip(INT ListIndex,INT OptionIndex=0);
    void ShopSellWeapon(INT InvenSlot);
    void ShopSellEquip(INT InvenSlot);
    UBOOL WICGetCash();
    UBOOL WICOpenChargeWindow();
    UBOOL WICBuyItem(INT idItem);
    UBOOL WICSendGift(INT idItem,INT idAccountTo);
    UBOOL WICOpenGiftWindow(INT idItem);
    void GuildJoinChannel();
    void GuildSetMotd(const FString& MOTD);
    void GuildChat(const FString& ChatMsg,UBOOL bParse=TRUE);
    void GuildNotice(const FString& NoticeMsg);
    void GuildLeave();
    void GuildKick(const FString& NickName);
    UBOOL GuildDoIHavePriv(INT Priv);
    void OptionSaveUserKey(const FString& UserKeyStr,const FString& OptionStr);
    void SelectPlayer(INT ListIndex);
    void SelectGuildPlayer(INT ListIndex);
    void SelectBuddy(INT ListIndex);
    void SelectBlock(INT ListIndex);
    FString GetCurrentChannelName();
    INT GetCurrentRoomIndex();
    INT GetCurrentRoomState();
    UBOOL GetCurrentRoomSetting(struct FavaRoomSetting& Setting);
    UBOOL GetCurrentEquipState(INT& MyTeam,INT& MyClass,INT& MyFace,INT& MyWeapon);
    INT GetMyRoomSlot();
    FString GetRandomRoomName();
    FString GetMapName(INT ListIndex);
    FString GetWeaponIconCode(INT idItem);
    FString GetWeaponName(INT idItem);
    FString GetSkillName(BYTE PlayerClass,INT SkillID);
    FString GetAwardName(INT AwardID);
    FString GetPlayerLevelName(INT PlayerLevel);
    UBOOL AmIHost();
    UBOOL AmISpectator();
    class UavaNetRequest* GetAvaNetRequest();
    DECLARE_FUNCTION(execAutoConnect)
    {
        P_GET_UBOOL(bForce);
        P_GET_STR_OPTX(USN,TEXT(""));
        P_GET_STR_OPTX(UserID,TEXT(""));
        P_GET_STR_OPTX(Key,TEXT(""));
        P_FINISH;
        *(UBOOL*)Result=AutoConnect(bForce,USN,UserID,Key);
    }
    DECLARE_FUNCTION(execCloseConnection)
    {
        P_GET_INT(ExitCode);
        P_FINISH;
        CloseConnection(ExitCode);
    }
    DECLARE_FUNCTION(execCreateCharacter)
    {
        P_GET_STR(NickName);
        P_GET_INT(FaceIndex);
        P_FINISH;
        CreateCharacter(NickName,FaceIndex);
    }
    DECLARE_FUNCTION(execQuit)
    {
        P_GET_UBOOL_OPTX(bGraceful,TRUE);
        P_FINISH;
        Quit(bGraceful);
    }
    DECLARE_FUNCTION(execListChannel)
    {
        P_FINISH;
        ListChannel();
    }
    DECLARE_FUNCTION(execJoinChannel)
    {
        P_GET_INT(ListIndex);
        P_FINISH;
        JoinChannel(ListIndex);
    }
    DECLARE_FUNCTION(execJoinChannelByID)
    {
        P_GET_INT(Id);
        P_GET_UBOOL_OPTX(bFollowing,FALSE);
        P_FINISH;
        JoinChannelByID(Id,bFollowing);
    }
    DECLARE_FUNCTION(execQuickJoinChannel)
    {
        P_GET_STR(Flags);
        P_FINISH;
        QuickJoinChannel(Flags);
    }
    DECLARE_FUNCTION(execLeaveChannel)
    {
        P_FINISH;
        LeaveChannel();
    }
    DECLARE_FUNCTION(execListRoom)
    {
        P_FINISH;
        ListRoom();
    }
    DECLARE_FUNCTION(execListLobbyPlayer)
    {
        P_FINISH;
        ListLobbyPlayer();
    }
    DECLARE_FUNCTION(execLobbySelectRoom)
    {
        P_GET_INT(ListIndex);
        P_FINISH;
        LobbySelectRoom(ListIndex);
    }
    DECLARE_FUNCTION(execCreateRoom)
    {
        P_GET_STR(RoomName);
        P_GET_STR(RoomPassword);
        P_GET_STRUCT(struct FavaRoomSetting,Setting);
        P_FINISH;
        CreateRoom(RoomName,RoomPassword,Setting);
    }
    DECLARE_FUNCTION(execJoinRoom)
    {
        P_GET_INT(ListIndex);
        P_GET_STR(RoomPassword);
        P_FINISH;
        *(UBOOL*)Result=JoinRoom(ListIndex,RoomPassword);
    }
    DECLARE_FUNCTION(execQuickJoinRoom)
    {
        P_GET_INT_OPTX(idMap,0);
        P_FINISH;
        *(UBOOL*)Result=QuickJoinRoom(idMap);
    }
    DECLARE_FUNCTION(execLeaveRoom)
    {
        P_GET_BYTE_OPTX(LeavingReason,0);
        P_FINISH;
        LeaveRoom(LeavingReason);
    }
    DECLARE_FUNCTION(execRoomKickPlayer)
    {
        P_GET_STR(NickName);
        P_GET_INT_OPTX(Reason,1);
        P_FINISH;
        RoomKickPlayer(NickName,Reason);
    }
    DECLARE_FUNCTION(execRoomSetting)
    {
        P_GET_STRUCT(struct FavaRoomSetting,Setting);
        P_FINISH;
        RoomSetting(Setting);
    }
    DECLARE_FUNCTION(execRoomReady)
    {
        P_GET_UBOOL(Ready);
        P_FINISH;
        RoomReady(Ready);
    }
    DECLARE_FUNCTION(execRoomReadyToggle)
    {
        P_FINISH;
        RoomReadyToggle();
    }
    DECLARE_FUNCTION(execRoomChangeTeam)
    {
        P_GET_INT(idTeam);
        P_FINISH;
        RoomChangeTeam(idTeam);
    }
    DECLARE_FUNCTION(execRoomChangeTeamToggle)
    {
        P_FINISH;
        RoomChangeTeamToggle();
    }
    DECLARE_FUNCTION(execRoomChangeSlot)
    {
        P_GET_INT(Slot);
        P_FINISH;
        RoomChangeSlot(Slot);
    }
    DECLARE_FUNCTION(execRoomChangeClass)
    {
        P_GET_INT(idClass);
        P_FINISH;
        RoomChangeClass(idClass);
    }
    DECLARE_FUNCTION(execRoomStart)
    {
        P_FINISH;
        RoomStart();
    }
    DECLARE_FUNCTION(execRoomCancelStart)
    {
        P_FINISH;
        RoomCancelStart();
    }
    DECLARE_FUNCTION(execRoomSwapTeam)
    {
        P_GET_INT_OPTX(Reason,0);
        P_FINISH;
        RoomSwapTeam(Reason);
    }
    DECLARE_FUNCTION(execRoomClaimHost)
    {
        P_FINISH;
        RoomClaimHost();
    }
    DECLARE_FUNCTION(execSetMyRttValue)
    {
        P_GET_FLOAT(RttValue);
        P_FINISH;
        SetMyRttValue(RttValue);
    }
    DECLARE_FUNCTION(execChat)
    {
        P_GET_STR(ChatMsg);
        P_FINISH;
        Chat(ChatMsg);
    }
    DECLARE_FUNCTION(execParseChatCommand)
    {
        P_GET_STR(Cmd);
        P_FINISH;
        *(UBOOL*)Result=ParseChatCommand(Cmd);
    }
    DECLARE_FUNCTION(execFilterChatMsg)
    {
        P_GET_STR_REF(ChatMsg);
        P_FINISH;
        FilterChatMsg(ChatMsg);
    }
    DECLARE_FUNCTION(execLeaveGame)
    {
        P_FINISH;
        LeaveGame();
    }
    DECLARE_FUNCTION(execBuddyListBegin)
    {
        P_FINISH;
        BuddyListBegin();
    }
    DECLARE_FUNCTION(execBuddyListEnd)
    {
        P_FINISH;
        BuddyListEnd();
    }
    DECLARE_FUNCTION(execBuddyAdd)
    {
        P_GET_UBOOL(bForce);
        P_GET_STR(NickName);
        P_FINISH;
        BuddyAdd(bForce,NickName);
    }
    DECLARE_FUNCTION(execBuddyAddAns)
    {
        P_GET_UBOOL(bAccept);
        P_GET_STR(NickName);
        P_FINISH;
        BuddyAddAns(bAccept,NickName);
    }
    DECLARE_FUNCTION(execBuddyDelete)
    {
        P_GET_STR(NickName);
        P_FINISH;
        BuddyDelete(NickName);
    }
    DECLARE_FUNCTION(execBlockAdd)
    {
        P_GET_UBOOL(bForce);
        P_GET_STR(NickName);
        P_FINISH;
        BlockAdd(bForce,NickName);
    }
    DECLARE_FUNCTION(execBlockDelete)
    {
        P_GET_STR(NickName);
        P_FINISH;
        BlockDelete(NickName);
    }
    DECLARE_FUNCTION(execWhisper)
    {
        P_GET_STR(NickName);
        P_GET_STR(ChatMsg);
        P_FINISH;
        Whisper(NickName,ChatMsg);
    }
    DECLARE_FUNCTION(execInviteGame)
    {
        P_GET_STR(NickName);
        P_FINISH;
        InviteGame(NickName);
    }
    DECLARE_FUNCTION(execInviteGameAns)
    {
        P_GET_UBOOL(bAccept);
        P_GET_STR(NickName);
        P_FINISH;
        InviteGameAns(bAccept,NickName);
    }
    DECLARE_FUNCTION(execFollowPlayer)
    {
        P_GET_STR(NickName);
        P_FINISH;
        FollowPlayer(NickName);
    }
    DECLARE_FUNCTION(execSetFollowPlayerPwd)
    {
        P_GET_STR(Password);
        P_FINISH;
        SetFollowPlayerPwd(Password);
    }
    DECLARE_FUNCTION(execInviteGuild)
    {
        P_GET_STR(NickName);
        P_FINISH;
        InviteGuild(NickName);
    }
    DECLARE_FUNCTION(execInviteGuildAns)
    {
        P_GET_UBOOL(bAccept);
        P_GET_STR(NickName);
        P_FINISH;
        InviteGuildAns(bAccept,NickName);
    }
    DECLARE_FUNCTION(execEnterInven)
    {
        P_FINISH;
        EnterInven();
    }
    DECLARE_FUNCTION(execLeaveInven)
    {
        P_FINISH;
        LeaveInven();
    }
    DECLARE_FUNCTION(execInvenSetWeapon)
    {
        P_GET_INT(EquipSlot);
        P_GET_INT(InvenSlot);
        P_FINISH;
        InvenSetWeapon(EquipSlot,InvenSlot);
    }
    DECLARE_FUNCTION(execInvenSetEquip)
    {
        P_GET_INT(EquipSlot);
        P_GET_INT(InvenSlot);
        P_FINISH;
        InvenSetEquip(EquipSlot,InvenSlot);
    }
    DECLARE_FUNCTION(execInvenSetCustom)
    {
        P_GET_INT(InvenSlot);
        P_GET_INT(CustomIndex);
        P_GET_INT_OPTX(OptionIndex,0);
        P_FINISH;
        InvenSetCustom(InvenSlot,CustomIndex,OptionIndex);
    }
    DECLARE_FUNCTION(execInvenSetEffect)
    {
        P_GET_INT(EquipSlot);
        P_GET_INT(InvenSlot);
        P_FINISH;
        InvenSetEffect(EquipSlot,InvenSlot);
    }
    DECLARE_FUNCTION(execInvenUnsetWeapon)
    {
        P_GET_INT(EquipSlot);
        P_GET_INT(InvenSlot);
        P_FINISH;
        InvenUnsetWeapon(EquipSlot,InvenSlot);
    }
    DECLARE_FUNCTION(execInvenUnsetEquip)
    {
        P_GET_INT(EquipSlot);
        P_GET_INT(InvenSlot);
        P_FINISH;
        InvenUnsetEquip(EquipSlot,InvenSlot);
    }
    DECLARE_FUNCTION(execInvenUnsetCustom)
    {
        P_GET_INT(InvenSlot);
        P_GET_INT(CustomSlot);
        P_FINISH;
        InvenUnsetCustom(InvenSlot,CustomSlot);
    }
    DECLARE_FUNCTION(execInvenUnsetEffect)
    {
        P_GET_INT(EquipSlot);
        P_GET_INT(InvenSlot);
        P_FINISH;
        InvenUnsetEffect(EquipSlot,InvenSlot);
    }
    DECLARE_FUNCTION(execInvenRepairWeapon)
    {
        P_GET_INT(InvenSlot);
        P_FINISH;
        InvenRepairWeapon(InvenSlot);
    }
    DECLARE_FUNCTION(execInvenRepairEquip)
    {
        P_GET_INT(InvenSlot);
        P_FINISH;
        InvenRepairEquip(InvenSlot);
    }
    DECLARE_FUNCTION(execInvenConvertRIS)
    {
        P_GET_INT(InvenSlot);
        P_FINISH;
        InvenConvertRIS(InvenSlot);
    }
    DECLARE_FUNCTION(execInvenGetWeaponRefundPrice)
    {
        P_GET_INT(InvenSlot);
        P_GET_INT_REF(Money);
        P_GET_INT_REF(Cash);
        P_FINISH;
        *(UBOOL*)Result=InvenGetWeaponRefundPrice(InvenSlot,Money,Cash);
    }
    DECLARE_FUNCTION(execInvenGetEquipRefundPrice)
    {
        P_GET_INT(InvenSlot);
        P_GET_INT_REF(Money);
        P_GET_INT_REF(Cash);
        P_FINISH;
        *(UBOOL*)Result=InvenGetEquipRefundPrice(InvenSlot,Money,Cash);
    }
    DECLARE_FUNCTION(execInvenGetCustomRefundPrice)
    {
        P_GET_INT(InvenSlot);
        P_GET_INT(CustomSlot);
        P_GET_INT_REF(Money);
        P_GET_INT_REF(Cash);
        P_FINISH;
        *(UBOOL*)Result=InvenGetCustomRefundPrice(InvenSlot,CustomSlot,Money,Cash);
    }
    DECLARE_FUNCTION(execGetUsedItemEffect)
    {
        P_GET_BYTE(ItemEffect);
        P_FINISH;
        *(INT*)Result=GetUsedItemEffect(ItemEffect);
    }
    DECLARE_FUNCTION(execShopBuyWeapon)
    {
        P_GET_INT(ListIndex);
        P_GET_INT_OPTX(OptionIndex,0);
        P_FINISH;
        ShopBuyWeapon(ListIndex,OptionIndex);
    }
    DECLARE_FUNCTION(execShopBuyEquip)
    {
        P_GET_INT(ListIndex);
        P_GET_INT_OPTX(OptionIndex,0);
        P_FINISH;
        ShopBuyEquip(ListIndex,OptionIndex);
    }
    DECLARE_FUNCTION(execShopSellWeapon)
    {
        P_GET_INT(InvenSlot);
        P_FINISH;
        ShopSellWeapon(InvenSlot);
    }
    DECLARE_FUNCTION(execShopSellEquip)
    {
        P_GET_INT(InvenSlot);
        P_FINISH;
        ShopSellEquip(InvenSlot);
    }
    DECLARE_FUNCTION(execWICGetCash)
    {
        P_FINISH;
        *(UBOOL*)Result=WICGetCash();
    }
    DECLARE_FUNCTION(execWICOpenChargeWindow)
    {
        P_FINISH;
        *(UBOOL*)Result=WICOpenChargeWindow();
    }
    DECLARE_FUNCTION(execWICBuyItem)
    {
        P_GET_INT(idItem);
        P_FINISH;
        *(UBOOL*)Result=WICBuyItem(idItem);
    }
    DECLARE_FUNCTION(execWICSendGift)
    {
        P_GET_INT(idItem);
        P_GET_INT(idAccountTo);
        P_FINISH;
        *(UBOOL*)Result=WICSendGift(idItem,idAccountTo);
    }
    DECLARE_FUNCTION(execWICOpenGiftWindow)
    {
        P_GET_INT(idItem);
        P_FINISH;
        *(UBOOL*)Result=WICOpenGiftWindow(idItem);
    }
    DECLARE_FUNCTION(execGuildJoinChannel)
    {
        P_FINISH;
        GuildJoinChannel();
    }
    DECLARE_FUNCTION(execGuildSetMotd)
    {
        P_GET_STR(MOTD);
        P_FINISH;
        GuildSetMotd(MOTD);
    }
    DECLARE_FUNCTION(execGuildChat)
    {
        P_GET_STR(ChatMsg);
        P_GET_UBOOL_OPTX(bParse,TRUE);
        P_FINISH;
        GuildChat(ChatMsg,bParse);
    }
    DECLARE_FUNCTION(execGuildNotice)
    {
        P_GET_STR(NoticeMsg);
        P_FINISH;
        GuildNotice(NoticeMsg);
    }
    DECLARE_FUNCTION(execGuildLeave)
    {
        P_FINISH;
        GuildLeave();
    }
    DECLARE_FUNCTION(execGuildKick)
    {
        P_GET_STR(NickName);
        P_FINISH;
        GuildKick(NickName);
    }
    DECLARE_FUNCTION(execGuildDoIHavePriv)
    {
        P_GET_INT(Priv);
        P_FINISH;
        *(UBOOL*)Result=GuildDoIHavePriv(Priv);
    }
    DECLARE_FUNCTION(execOptionSaveUserKey)
    {
        P_GET_STR(UserKeyStr);
        P_GET_STR(OptionStr);
        P_FINISH;
        OptionSaveUserKey(UserKeyStr,OptionStr);
    }
    DECLARE_FUNCTION(execSelectPlayer)
    {
        P_GET_INT(ListIndex);
        P_FINISH;
        SelectPlayer(ListIndex);
    }
    DECLARE_FUNCTION(execSelectGuildPlayer)
    {
        P_GET_INT(ListIndex);
        P_FINISH;
        SelectGuildPlayer(ListIndex);
    }
    DECLARE_FUNCTION(execSelectBuddy)
    {
        P_GET_INT(ListIndex);
        P_FINISH;
        SelectBuddy(ListIndex);
    }
    DECLARE_FUNCTION(execSelectBlock)
    {
        P_GET_INT(ListIndex);
        P_FINISH;
        SelectBlock(ListIndex);
    }
    DECLARE_FUNCTION(execGetCurrentChannelName)
    {
        P_FINISH;
        *(FString*)Result=GetCurrentChannelName();
    }
    DECLARE_FUNCTION(execGetCurrentRoomIndex)
    {
        P_FINISH;
        *(INT*)Result=GetCurrentRoomIndex();
    }
    DECLARE_FUNCTION(execGetCurrentRoomState)
    {
        P_FINISH;
        *(INT*)Result=GetCurrentRoomState();
    }
    DECLARE_FUNCTION(execGetCurrentRoomSetting)
    {
        P_GET_STRUCT_REF(struct FavaRoomSetting,Setting);
        P_FINISH;
        *(UBOOL*)Result=GetCurrentRoomSetting(Setting);
    }
    DECLARE_FUNCTION(execGetCurrentEquipState)
    {
        P_GET_INT_REF(MyTeam);
        P_GET_INT_REF(MyClass);
        P_GET_INT_REF(MyFace);
        P_GET_INT_REF(MyWeapon);
        P_FINISH;
        *(UBOOL*)Result=GetCurrentEquipState(MyTeam,MyClass,MyFace,MyWeapon);
    }
    DECLARE_FUNCTION(execGetMyRoomSlot)
    {
        P_FINISH;
        *(INT*)Result=GetMyRoomSlot();
    }
    DECLARE_FUNCTION(execGetRandomRoomName)
    {
        P_FINISH;
        *(FString*)Result=GetRandomRoomName();
    }
    DECLARE_FUNCTION(execGetMapName)
    {
        P_GET_INT(ListIndex);
        P_FINISH;
        *(FString*)Result=GetMapName(ListIndex);
    }
    DECLARE_FUNCTION(execGetWeaponIconCode)
    {
        P_GET_INT(idItem);
        P_FINISH;
        *(FString*)Result=GetWeaponIconCode(idItem);
    }
    DECLARE_FUNCTION(execGetWeaponName)
    {
        P_GET_INT(idItem);
        P_FINISH;
        *(FString*)Result=GetWeaponName(idItem);
    }
    DECLARE_FUNCTION(execGetSkillName)
    {
        P_GET_BYTE(PlayerClass);
        P_GET_INT(SkillID);
        P_FINISH;
        *(FString*)Result=GetSkillName(PlayerClass,SkillID);
    }
    DECLARE_FUNCTION(execGetAwardName)
    {
        P_GET_INT(AwardID);
        P_FINISH;
        *(FString*)Result=GetAwardName(AwardID);
    }
    DECLARE_FUNCTION(execGetPlayerLevelName)
    {
        P_GET_INT(PlayerLevel);
        P_FINISH;
        *(FString*)Result=GetPlayerLevelName(PlayerLevel);
    }
    DECLARE_FUNCTION(execAmIHost)
    {
        P_FINISH;
        *(UBOOL*)Result=AmIHost();
    }
    DECLARE_FUNCTION(execAmISpectator)
    {
        P_FINISH;
        *(UBOOL*)Result=AmISpectator();
    }
    DECLARE_FUNCTION(execGetAvaNetRequest)
    {
        P_FINISH;
        *(class UavaNetRequest**)Result=GetAvaNetRequest();
    }
    DECLARE_CLASS(UavaNetRequest,UObject,0|CLASS_Config,AVANET)
    static const TCHAR* StaticConfigName() {return TEXT("NET");}

public:
	void NPGameSendAuth(DWORD dwIndex, DWORD dwValue1, DWORD dwValue2, DWORD dwValue3);

	/** 미션타입에 따른 방설정을 반환 */
	FavaRoomSetting* GetCurrentRoomSetting( INT CurrentMissionType );
	void ResetRoomSettingsAsDefault();
};

#endif

AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGetAvaNetRequest);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execAmISpectator);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execAmIHost);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGetPlayerLevelName);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGetAwardName);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGetSkillName);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGetWeaponName);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGetWeaponIconCode);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGetMapName);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGetRandomRoomName);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGetMyRoomSlot);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGetCurrentEquipState);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGetCurrentRoomSetting);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGetCurrentRoomState);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGetCurrentRoomIndex);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGetCurrentChannelName);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execSelectBlock);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execSelectBuddy);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execSelectGuildPlayer);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execSelectPlayer);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execOptionSaveUserKey);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGuildDoIHavePriv);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGuildKick);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGuildLeave);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGuildNotice);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGuildChat);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGuildSetMotd);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGuildJoinChannel);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execWICOpenGiftWindow);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execWICSendGift);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execWICBuyItem);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execWICOpenChargeWindow);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execWICGetCash);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execShopSellEquip);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execShopSellWeapon);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execShopBuyEquip);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execShopBuyWeapon);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execGetUsedItemEffect);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInvenGetCustomRefundPrice);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInvenGetEquipRefundPrice);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInvenGetWeaponRefundPrice);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInvenConvertRIS);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInvenRepairEquip);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInvenRepairWeapon);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInvenUnsetEffect);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInvenUnsetCustom);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInvenUnsetEquip);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInvenUnsetWeapon);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInvenSetEffect);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInvenSetCustom);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInvenSetEquip);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInvenSetWeapon);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execLeaveInven);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execEnterInven);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInviteGuildAns);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInviteGuild);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execSetFollowPlayerPwd);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execFollowPlayer);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInviteGameAns);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execInviteGame);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execWhisper);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execBlockDelete);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execBlockAdd);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execBuddyDelete);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execBuddyAddAns);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execBuddyAdd);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execBuddyListEnd);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execBuddyListBegin);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execLeaveGame);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execFilterChatMsg);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execParseChatCommand);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execChat);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execSetMyRttValue);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execRoomClaimHost);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execRoomSwapTeam);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execRoomCancelStart);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execRoomStart);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execRoomChangeClass);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execRoomChangeSlot);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execRoomChangeTeamToggle);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execRoomChangeTeam);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execRoomReadyToggle);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execRoomReady);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execRoomSetting);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execRoomKickPlayer);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execLeaveRoom);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execQuickJoinRoom);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execJoinRoom);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execCreateRoom);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execLobbySelectRoom);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execListLobbyPlayer);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execListRoom);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execLeaveChannel);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execQuickJoinChannel);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execJoinChannelByID);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execJoinChannel);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execListChannel);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execQuit);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execCreateCharacter);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execCloseConnection);
AUTOGENERATE_FUNCTION(UavaNetRequest,-1,execAutoConnect);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#ifdef STATIC_LINKING_MOJO
#ifndef AVANET_NATIVE_DEFS
#define AVANET_NATIVE_DEFS

DECLARE_NATIVE_TYPE(AVANET,UavaNetRequest);

#define AUTO_INITIALIZE_REGISTRANTS_AVANET \
	UavaNetRequest::StaticClass(); \
	GNativeLookupFuncs[Lookup++] = &FindAVANETUavaNetRequestNative; \

#endif // AVANET_NATIVE_DEFS

#ifdef NATIVES_ONLY
NATIVE_INFO(UavaNetRequest) GAVANETUavaNetRequestNatives[] = 
{ 
	MAP_NATIVE(UavaNetRequest,execGetAvaNetRequest)
	MAP_NATIVE(UavaNetRequest,execAmISpectator)
	MAP_NATIVE(UavaNetRequest,execAmIHost)
	MAP_NATIVE(UavaNetRequest,execGetPlayerLevelName)
	MAP_NATIVE(UavaNetRequest,execGetAwardName)
	MAP_NATIVE(UavaNetRequest,execGetSkillName)
	MAP_NATIVE(UavaNetRequest,execGetWeaponName)
	MAP_NATIVE(UavaNetRequest,execGetWeaponIconCode)
	MAP_NATIVE(UavaNetRequest,execGetMapName)
	MAP_NATIVE(UavaNetRequest,execGetRandomRoomName)
	MAP_NATIVE(UavaNetRequest,execGetMyRoomSlot)
	MAP_NATIVE(UavaNetRequest,execGetCurrentEquipState)
	MAP_NATIVE(UavaNetRequest,execGetCurrentRoomSetting)
	MAP_NATIVE(UavaNetRequest,execGetCurrentRoomState)
	MAP_NATIVE(UavaNetRequest,execGetCurrentRoomIndex)
	MAP_NATIVE(UavaNetRequest,execGetCurrentChannelName)
	MAP_NATIVE(UavaNetRequest,execSelectBlock)
	MAP_NATIVE(UavaNetRequest,execSelectBuddy)
	MAP_NATIVE(UavaNetRequest,execSelectGuildPlayer)
	MAP_NATIVE(UavaNetRequest,execSelectPlayer)
	MAP_NATIVE(UavaNetRequest,execOptionSaveUserKey)
	MAP_NATIVE(UavaNetRequest,execGuildDoIHavePriv)
	MAP_NATIVE(UavaNetRequest,execGuildKick)
	MAP_NATIVE(UavaNetRequest,execGuildLeave)
	MAP_NATIVE(UavaNetRequest,execGuildNotice)
	MAP_NATIVE(UavaNetRequest,execGuildChat)
	MAP_NATIVE(UavaNetRequest,execGuildSetMotd)
	MAP_NATIVE(UavaNetRequest,execGuildJoinChannel)
	MAP_NATIVE(UavaNetRequest,execWICOpenGiftWindow)
	MAP_NATIVE(UavaNetRequest,execWICSendGift)
	MAP_NATIVE(UavaNetRequest,execWICBuyItem)
	MAP_NATIVE(UavaNetRequest,execWICOpenChargeWindow)
	MAP_NATIVE(UavaNetRequest,execWICGetCash)
	MAP_NATIVE(UavaNetRequest,execShopSellEquip)
	MAP_NATIVE(UavaNetRequest,execShopSellWeapon)
	MAP_NATIVE(UavaNetRequest,execShopBuyEquip)
	MAP_NATIVE(UavaNetRequest,execShopBuyWeapon)
	MAP_NATIVE(UavaNetRequest,execGetUsedItemEffect)
	MAP_NATIVE(UavaNetRequest,execInvenGetCustomRefundPrice)
	MAP_NATIVE(UavaNetRequest,execInvenGetEquipRefundPrice)
	MAP_NATIVE(UavaNetRequest,execInvenGetWeaponRefundPrice)
	MAP_NATIVE(UavaNetRequest,execInvenConvertRIS)
	MAP_NATIVE(UavaNetRequest,execInvenRepairEquip)
	MAP_NATIVE(UavaNetRequest,execInvenRepairWeapon)
	MAP_NATIVE(UavaNetRequest,execInvenUnsetEffect)
	MAP_NATIVE(UavaNetRequest,execInvenUnsetCustom)
	MAP_NATIVE(UavaNetRequest,execInvenUnsetEquip)
	MAP_NATIVE(UavaNetRequest,execInvenUnsetWeapon)
	MAP_NATIVE(UavaNetRequest,execInvenSetEffect)
	MAP_NATIVE(UavaNetRequest,execInvenSetCustom)
	MAP_NATIVE(UavaNetRequest,execInvenSetEquip)
	MAP_NATIVE(UavaNetRequest,execInvenSetWeapon)
	MAP_NATIVE(UavaNetRequest,execLeaveInven)
	MAP_NATIVE(UavaNetRequest,execEnterInven)
	MAP_NATIVE(UavaNetRequest,execInviteGuildAns)
	MAP_NATIVE(UavaNetRequest,execInviteGuild)
	MAP_NATIVE(UavaNetRequest,execSetFollowPlayerPwd)
	MAP_NATIVE(UavaNetRequest,execFollowPlayer)
	MAP_NATIVE(UavaNetRequest,execInviteGameAns)
	MAP_NATIVE(UavaNetRequest,execInviteGame)
	MAP_NATIVE(UavaNetRequest,execWhisper)
	MAP_NATIVE(UavaNetRequest,execBlockDelete)
	MAP_NATIVE(UavaNetRequest,execBlockAdd)
	MAP_NATIVE(UavaNetRequest,execBuddyDelete)
	MAP_NATIVE(UavaNetRequest,execBuddyAddAns)
	MAP_NATIVE(UavaNetRequest,execBuddyAdd)
	MAP_NATIVE(UavaNetRequest,execBuddyListEnd)
	MAP_NATIVE(UavaNetRequest,execBuddyListBegin)
	MAP_NATIVE(UavaNetRequest,execLeaveGame)
	MAP_NATIVE(UavaNetRequest,execFilterChatMsg)
	MAP_NATIVE(UavaNetRequest,execParseChatCommand)
	MAP_NATIVE(UavaNetRequest,execChat)
	MAP_NATIVE(UavaNetRequest,execSetMyRttValue)
	MAP_NATIVE(UavaNetRequest,execRoomClaimHost)
	MAP_NATIVE(UavaNetRequest,execRoomSwapTeam)
	MAP_NATIVE(UavaNetRequest,execRoomCancelStart)
	MAP_NATIVE(UavaNetRequest,execRoomStart)
	MAP_NATIVE(UavaNetRequest,execRoomChangeClass)
	MAP_NATIVE(UavaNetRequest,execRoomChangeSlot)
	MAP_NATIVE(UavaNetRequest,execRoomChangeTeamToggle)
	MAP_NATIVE(UavaNetRequest,execRoomChangeTeam)
	MAP_NATIVE(UavaNetRequest,execRoomReadyToggle)
	MAP_NATIVE(UavaNetRequest,execRoomReady)
	MAP_NATIVE(UavaNetRequest,execRoomSetting)
	MAP_NATIVE(UavaNetRequest,execRoomKickPlayer)
	MAP_NATIVE(UavaNetRequest,execLeaveRoom)
	MAP_NATIVE(UavaNetRequest,execQuickJoinRoom)
	MAP_NATIVE(UavaNetRequest,execJoinRoom)
	MAP_NATIVE(UavaNetRequest,execCreateRoom)
	MAP_NATIVE(UavaNetRequest,execLobbySelectRoom)
	MAP_NATIVE(UavaNetRequest,execListLobbyPlayer)
	MAP_NATIVE(UavaNetRequest,execListRoom)
	MAP_NATIVE(UavaNetRequest,execLeaveChannel)
	MAP_NATIVE(UavaNetRequest,execQuickJoinChannel)
	MAP_NATIVE(UavaNetRequest,execJoinChannelByID)
	MAP_NATIVE(UavaNetRequest,execJoinChannel)
	MAP_NATIVE(UavaNetRequest,execListChannel)
	MAP_NATIVE(UavaNetRequest,execQuit)
	MAP_NATIVE(UavaNetRequest,execCreateCharacter)
	MAP_NATIVE(UavaNetRequest,execCloseConnection)
	MAP_NATIVE(UavaNetRequest,execAutoConnect)
	{NULL,NULL}
};
IMPLEMENT_NATIVE_HANDLER(AVANET,UavaNetRequest);

#endif // NATIVES_ONLY
#endif // STATIC_LINKING_MOJO

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_OFFSET_NODIE(U,avaNetRequest,ChannelList)
VERIFY_CLASS_OFFSET_NODIE(U,avaNetRequest,RoomSettingTyped)
VERIFY_CLASS_SIZE_NODIE(UavaNetRequest)
#endif // VERIFY_CLASS_SIZES
#endif // !ENUMS_ONLY

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
